### ISSUE TITLE
Crop circles panel appears for all players

### ISSUE THREAD

**Issue by LevenGyula** [farin/JCloisterZone#101]
One of the players drew a tile with crop circles, then the transparent panel with the two buttons appeared not only for him but for all the other players as well. The active player selected one of the two options (made a decision that all players may add another follower), but after that an other player hit the other button (all players should remove a follower), and finally the latter action decided the effect of the crop circles, although it wasn't made by the active player.

--- reported with -----
3.0.2 2014-11-02 
Windows 7 x86 6.1
Oracle Corporation 1.8.0_25

**Comment by farin** [comment]
should be fixed in 3.1.0
