### ISSUE TITLE
unnecessary scrollbar in setup game dialog

### ISSUE THREAD

**Issue by farin** [farin/JCloisterZone#108]
- I have the scroll bar as well, even on a 1920x1200 display.  Nothing is hidden, so I am not sure why a scroll bar is needed.
- Well, my old laptop monitor is set on 1440x900 and it has the scrollbar. No problem at all, I just did not notice it before, because on 3.0.2 without M&W everything just fitted on the screen, and it looked like, everything should still be visible with one more line.

**Comment by Hounk** [comment]
I was the guy with the "old 1440 x 900" laptop. My new machine is set to 1920 x 1080 and does not have this issue. (Neither on 3.1.1 nor on 3.2.)

**Comment by farin** [comment]
not relevant for 5.x
