### ISSUE TITLE
extended stats

### ISSUE THREAD

**Issue by farin** [farin/JCloisterZone#109]
someone from CC discussion:
I've just got an idea that doesn't take much time and work to implement:
Playing with "Traders & Builders", it would be nice to know, how efficiently the builder was used by every player.
I see it as an additional line in the results window in a very simple manner: "Tiles drawn" (or "Tiles placed").
Since it is a very popular expansion and is used in almost every game, I think this information is good to know.

**Comment by Cu8eR** [comment]
Nice! Good idea!

**Comment by fatsu** [comment]
Sounds good. 

But why wait for the results screen? It could already be shown during the game in the PlayerPanel.

I suppose there are several ways to display this info: 
- as Builder usage counter (incremental): +B
- actual drawn tile count: _drawn_tiles_ of _total_drawn_tiles_
- as percentage: Y%  (_drawn_tiles_ / _total_drawn_tiles_)
- as a difference compared to the 'normal' average per player: +|- X ((_total_drawn_tiles_ / _#_players_) - _drawn_tiles_)

... with some tweaking on the rounding...
