### ISSUE TITLE
Highlight tiles which have been putted by other players on their last turn

### ISSUE THREAD

**Issue by alekstar** [farin/JCloisterZone#122]
Highlight tiles which have been putted by other players on their last turn with rectangle colored with player's color.

**Comment by farin** [comment]
use x key (or menu item) to toggle show placemeny history

**Comment by fatsu** [comment]
@farin: 
That was my first thought too, but, it's sometimes difficult to see the last tile placement numbers over the tiles. Adding (thin) border in the players color would make it easier to spot which player put which tile, certainly when playing with the Builder.

**Comment by farin** [comment]
ok, i will be thinking about some improvements

**Comment by farin** [comment]
idea: add outer glow in player color

**Comment by Cu8eR** [comment]
it sounds good!

**Comment by farin** [comment]
arrows around corners are present in 5.x
