### ISSUE TITLE
scoring bug: Inns & Cathedrals expansion does not score large meeple correclty on roads/cities 

### ISSUE THREAD

**Issue by sicem** [farin/JCloisterZone#125]
Noticed when playing with Inns and Cathedrals expansion, instead of scoring completed cities and roads correctly (with extra points) when large 2x meeple is used, that the robber baron and king symbols are displayed instead (even though the king and robber baron expansion is not selected).

**Comment by farin** [comment]
large meeple don't provide any extra points. 
Could you attach screenshot with king/robber symbols?
