### ISSUE TITLE
Zooming bug

### ISSUE THREAD

**Issue by CasualSmile** [farin/JCloisterZone#13]
When the game starts, the zooming in and out with the mousewheel is not working, and remains so until either
- a window pops up for any reason (close confirmation, controls window, highscore table, etc.)
- the game window is minimized and reopened.

I assume there is a focus gain error at the beginning, although keyboard zooming works well, only mouse scrolling not, and any other mouse function works properly.

**Comment by farin** [comment]
@CasualSmile is is still valid for latest jcz?
