### ISSUE TITLE
Passing at game end does not work

### ISSUE THREAD

**Issue by LevenGyula** [farin/JCloisterZone#136]
![pass01](https://cloud.githubusercontent.com/assets/10690151/7419630/a28a73a4-ef76-11e4-9140-b9c6ecf5cdc8.JPG)
The final score window does not appear if the player who draws the last tile has no available action. The Pass button appears along with the following message: "No action available. Pass or undo tile placement." But nothing happens after clicking on the button, we cannot see the final score window.

**Comment by farin** [comment]
not happen for me in current dev, let's verify it with next release
