### ISSUE TITLE
Fairy scoring is outdated

### ISSUE THREAD

**Issue by LevenGyula** [farin/JCloisterZone#137]
According to the current HiG rules (see CAR) when a player moves the fairy he/she has to move it NEXT TO one of his/her followers. That is, only one follower can be next to (or connected to) the fairy, thus only one follower can receive points from the fairy in the following effects:
- At the start of the player's turn, if the fairy is NEXT TO one of the player's followers, the player scores 1 pont.
- If the fairy is standing NEXT TO a follower in a feature that is being scored, the owner of that follower receives 3 points.
JCZ still uses the old scoring rule where the player could receive points even if his/her follower was standing ON THE SAME TILE where the fairy stood. This should be changed or at least there should be an option in the game settings to switch to the new ruling.

**Comment by farin** [comment]
yes i know, i would like to support both ways with rule option.
