### ISSUE TITLE
ai & big follower

### ISSUE THREAD

**Issue by farin** [farin/JCloisterZone#140]
Playing against AI using 3.2.0.  
AI has first move and draws a Cloister.  
AI claims Cloister with the Big Follower.  

I would suggest that this is rather overkill for a cloister which is a single tile structure and there is no possible way I could contest it.

**Comment by Hounk** [comment]
I think, AI always uses Big Follower, whenever available. On the other hand, the Mayor is always spared for the time, when no other follower is in supply. Even on attempts to sneak into a city with already many pennants it uses rather a normal follower (or of course the big guy) instead.
