### ISSUE TITLE
improved undo

### ISSUE THREAD

**Issue by farin** [farin/JCloisterZone#144]
rfiedler: 

In 3.2.0, the Undo has changed.  There are more actions that can be undone.  This was a very good change.

Can this go a little bit further?  The scenario:
- place a tile
- place a meeple

leaves you with the ability to undo the meeple placement.

I would like to suggest that you then be allowed to also under the tile placement.  In other words, the first Ctrl-Z would undo the meeple placement, and a second Ctrl-Z would undo the tile placement.

**Comment by oevans** [comment]
+1!

**Comment by farin** [comment]
possible in 4.x
