### ISSUE TITLE
Missing farms on Abbey & Mayor tiles

### ISSUE THREAD

**Issue by Hounk** [farin/JCloisterZone#147]
There are two tiles in A&M with one city segment bridging over another, both with one or two tiny areas of gras in between. Although they can serve max. 2 cities and therefore are not very likely used in most games, it should be possible to place there a farmer, which is not.

**Comment by farin** [comment]
I think that some rule disallow placement here. But now I can't find the source. I will make research about it.

**Comment by farin** [comment]
hmm it's surprise for me, but i was probably mistaken and the placement should be legal.

**Comment by Hounk** [comment]
I can't figure out any difference to the tiles with two city-segments without road in "Traders & Builder", nor find any specifications on HiG or CAR, that it's illegal here.
