### ISSUE TITLE
Skip bug (not only Asus t100?)

### ISSUE THREAD

**Issue by Dadibom** [farin/JCloisterZone#153]
Very often when a player has placed a tile, the skip button is unpressable. This is resolved by saving, restarting and loading. It's very annoying.

**Comment by farin** [comment]
Hi, 
could you tell me, your platform/OS. What is you game settings? Is it play against computer?
And selected expansions please.

**Comment by Dadibom** [comment]
Windows 8, asus t100. Standard settings, no expansions, 2 human players

Date: Sun, 28 Jun 2015 13:56:08 -0700

**Comment by farin** [comment]
thx, btw Skip button should be activated also by pressing space? doest it also didn't work?

**Comment by Dadibom** [comment]
Didn't have a keyboard attached when it happened so i haven't tried!

Date: Sun, 28 Jun 2015 15:12:13 -0700

**Comment by x-iso** [comment]
This happens pretty often to some players, me included. When you have a situation where you can only skip the turn, the "skip" button sometimes persists (even when other people doing their turns) until you quit and rejoin the game or even restart the app and rejoin.

**Comment by Dadibom** [comment]
Yeah, though my problem means that there's no way to keep playing.

Date: Fri, 31 Jul 2015 16:35:25 -0700

**Comment by x-iso** [comment]
Yes some people report that no matter what they do, it still shows skip button and you can't do anything. In my case complete restart of the app and rejoining the game solves the problem. I wonder if it's same or similar bug.

**Comment by Dadibom** [comment]
Same for me. Closing the app and reloading the game is the only way

Date: Sat, 1 Aug 2015 04:21:21 -0700

**Comment by farin** [comment]
@x-iso You saying pretty ofter. Then could you try to use "Report bug" in help menu when it happen and send it to me. If you catch it more times it would better. I have no much idea what can cause it and this could helps.

One importatn question, for all @x-iso @Dadibom Do you remeber if you host game, or did you connect to remote host or use "play online" It could be also important

**Comment by Dadibom** [comment]
In my case, just a local game. Happens 4-5 times per game with 1-2 expansions.

Date: Sat, 1 Aug 2015 12:18:57 -0700

**Comment by farin** [comment]
Just saw it on my own eys on my local game
Observation: 
seem it is no related to game state 
happen early on fifth tile - played again with exactly same tiles and actions - not happen again

It's probably related rather to some window state (it can be anything ike minimize, using zoom ... etc) or just there is a bad timing.

**Comment by Dadibom** [comment]
Yeah we don't zoom or anything. We were just playing and it kept happening every time. :(

Date: Sat, 1 Aug 2015 12:58:30 -0700

**Comment by farin** [comment]
I need help. Unforutunatelly this issue happen very rarely on my machine (saw it just once)
But I have one idea, so please if you could check second beta with a blind experimental fix  it would be great:
http://jcloisterzone.com/builds/JCloisterZone-3.3.0-beta2.7z
or
http://jcloisterzone.com/builds/JCloisterZone-3.3.0-beta2.zip

**Comment by Dadibom** [comment]
I will try it out asap!

Date: Sun, 2 Aug 2015 05:08:38 -0700

**Comment by x-iso** [comment]
tried, but got nothing so far. would be better to be able to test it online (which is unavailable for this build), I get it there more often (well, maybe because I play online more often)

**Comment by farin** [comment]
yeah, I know about it, current play server can't handle two different version. But it's shouldn't be hard to change. I will try to improve this before releasing 3.3.0.

**Comment by x-iso** [comment]
I just thought of one thing, the reason why I had this more often online is also because more people were involved and if not me, at least someone would experience this from time to time. You have to play with more than 2 players and avoid using AI to increase chance of having this bug.
