### ISSUE TITLE
Not every follower can be selected to move the fairy next to

### ISSUE THREAD

**Issue by joti** [farin/JCloisterZone#159]
See attached images.
1. I intended to move the fairy next to the yellow follower on the right side but the JCZ (3.3.0) did not allow it to me (the yellow circle did not appear around it).
2. But it allowed me to move the fairy next to my other follower on the left side.
3. Later in the game also the follower on the right side could be selected for fairy movement.
I don't see any reason not allowing it earlier.
![fairy_moving1](https://cloud.githubusercontent.com/assets/10690151/8766166/3bfae4e8-2e2d-11e5-9ee7-bb645c1d296e.jpg)
![fairy_moving2](https://cloud.githubusercontent.com/assets/10690151/8766167/3bfb1292-2e2d-11e5-88ff-a47bf968892f.jpg)
![fairy_moving3](https://cloud.githubusercontent.com/assets/10690151/8766165/3bf91e4c-2e2d-11e5-9730-26fa99c49a13.jpg)

**Comment by farin** [comment]
unable to simulate, so if you observe in regular 3.3.0 please let me know
