### ISSUE TITLE
New Players execute the jar from within the zip

### ISSUE THREAD

**Issue by Decar** [farin/JCloisterZone#160]
A small usability issue: Windows handles ZIP files in a terrible way.  It displays them as folders.  We've had numerous new players attempt execute the JCZ jar file; join a game and then be unable to play because the JRE is unable to load the other resources which were not unpacked from within the jar.

New players complain of not seeing anything or just black images.  It also means any games they managed to join are broken.

I think the main application should attempt to load some of these resources before the game begins and warn the user that the resources could not be found (probably because the JAR was executed from within an archive and it needs to be unpacked).

**Comment by joelpurra** [comment]
@Decar: agreed. Had this problem multiple times -- even repeatedly for those who aren't very computer-savvy.

**Comment by farin** [comment]
good point
one possible solution is offer self executable exe as default for win plaform
tgz for unix base plaforms
and  7zip for people who don't like exe

**Comment by Cu8eR** [comment]
.exe file would be great
