### ISSUE TITLE
Autostart Options

### ISSUE THREAD

**Issue by Decar** [farin/JCloisterZone#161]
Would anyone object if I added a parameter/option to the Autostart config so that the game was auto-created, but not automatically started?

It would be quite handy to be able to start JCZ on the 'New Game' page.  It means I could host sessions remotely etc.

It should just need an extra parameter and check on the ClientMessageListener.java before conn.send(new StartGameMessage(game.getGameId())); is called.

**Comment by farin** [comment]
if you want host games you may find handy this command

java -cp JCloisterZone.jar com.jcloisterzone.wsio.server.SimpleServer

it creates server with created game, listening to connections. When games finished new one is automatically created. No ui is displayed.

**Comment by Decar** [comment]
Well that's a million times better!

I will give it a go, and close this issue tonight!

Tom

**Comment by Decar** [comment]
This has been awesome, wish I did it month ago!

It would be handy to have this recorded in the Building.md or somewhere
