### ISSUE TITLE
Prefences dialog don't fit some translations.

### ISSUE THREAD

**Issue by farin** [farin/JCloisterZone#165]
in the Preferences window you could leave more space for the labels. Sometimes the translation is a longer text than the original one, and therefore may not fit to the current space.

(hungarian translation)

**Comment by JJ-OpenTTD** [comment]
I have spotted the same problem in Help->About and Help->Report bug.
![jcz-5](https://cloud.githubusercontent.com/assets/3152990/9383931/0052b392-474d-11e5-94e0-75f18567055e.png)
![jcz-6](https://cloud.githubusercontent.com/assets/3152990/9383932/01adbcaa-474d-11e5-9918-8171f69e2737.png)

Window panels could be sized taking into account how long is the string to be shown (this would work for most languages) or breaking lines for strings that are too long.
