### ISSUE TITLE
Tile placement not taking into account unfinished river edge

### ISSUE THREAD

**Issue by fatsu** [farin/JCloisterZone#167]
We were allowed to place a straigth road (tile 1), even though there was an unfinished river (since #155) on the south edge. (version 3.3.0-beta)

![board](https://cloud.githubusercontent.com/assets/10167314/8955816/612b93f0-35f0-11e5-92f4-7776bbb63f02.png)

**Comment by farin** [comment]
#2a3860261616506312b9066304df80c613ae8a9f fixes it
