### ISSUE TITLE
Apostrophes not shown

### ISSUE THREAD

**Issue by JJ-OpenTTD** [farin/JCloisterZone#177]
Using Catalan translation, the "Abbey & Mayor" expansion is translated as "L'abadia i l'alcalde". In the application it is shown as "Labadia i lalcalde", deleting all apostrophes.
![jcz-2](https://cloud.githubusercontent.com/assets/3152990/9381249/e63b5da4-4735-11e5-8c3c-ea5a982ffc8c.png)

**Comment by farin** [comment]
btw http://stackoverflow.com/questions/4449639/apostrophe-doesnt-get-translated-properly-when-placed-in-a-resource-bundle

**Comment by JJ-OpenTTD** [comment]
Thank you! I didn't know I had to write two apostrophes in those cases!!

Maybe this string in English is also affected: "It's not possible to place mage or witch because there isn't an unfinished "

Thank you again!

**Comment by farin** [comment]
Neither me. You're right, english string is affected too.
