### ISSUE TITLE
Redesign a new game configuration

### ISSUE THREAD

**Issue by J0anJosep** [farin/JCloisterZone#179]
I think there is too much information when you are creating a new game. There is a chat, presets tool, players selection, time, expansions and custom rules. It is inconvenient because you have to scroll horizontally and vertically and it is difficult to have an overview of what you have selected.

I would suggest a window with tabs. The chat is ok as it is. But possibly making 4 tabs for the rest of the information could be better: the first tab for player and time configuration, the second for expansions, the third for custom rules and the fourth for reviewing the whole configuration (and presets).

In the tab for expansions, a mark could be added for expansions that have specific custom rules.

And in the tab for custom rules, it could be possible to hide the custom rules for a not selected expansion. In other words, if I haven't selected "The princess and the dragon", I shouldn't see the custom rules for the expansion.

**Comment by farin** [comment]
related to #62 #63
this definitelly needs game setup redesign

**Comment by x-iso** [comment]
I would strongly disagree about tabbed interface for game setup though. I do need to see all options at once, especially in online mode when other players can change settings I have to be able to keep track of it. Still, hiding irrelevant rule overrides/settings is necessary either way.

What setup windows does need is a check box for "ready" status required for all players to start the game. I had plenty of cases when someone would join and redo all the settings, then start the game. All while the app was in background and I was busy with something else.

Also, as I mentioned before in other request tabs would make sense to switch between different games and lobby.

**Comment by farin** [comment]
don't worry, I also think that tabs are not proper solutions

**Comment by JJ-OpenTTD** [comment]
I haven't played online, but the "Ready" status seems useful for not allowing changing settings before starting the game.
Tabs can be used for switching between different games and the lobby, but the lobby itself can also have a "tabbed" or similar GUI.

Maybe the steps could be:
1) Select expansions. Some other features such as "Select how many of these sets of tiles to use" could be added here. Probably, there would be space enough for a brief description of the last selected expansion, and also mark the expansions that have custom rules and those that cannot be played with AI players.
2) Select custom rules. Only list the custom rules that are involved with the expansions selected in step 1.
3) Review settings (show what has been selected in steps 1 and 2) +
     "Ready" button (when a player presses the button, settings cannot be changed anymore) + 
     "Presets"
4) Players and "Start game". 

Maybe tabs are not the best solution to the problem, but I can't figure out a better one. Anyway, I think there should be a more step-by-step approach for choosing the settings for a new game.

**Comment by x-iso** [comment]
The way I see it, only problem is that with small resolution or window size you have to use both vertical and horizontal scrolling. So the solution would be to optimize it for horizontal scrolling (in case you have small resolution or window). List of add-ons should split in two columns with less than enough vertical space, it also could have separate column for add-ons not available to play with AI. List of rules should use wrapping to make it horizontally thinner and hide irrelevant options.

**Comment by farin** [comment]
5.x has completely new game setup
