### ISSUE TITLE
No bonus turn for builder due to volcano tile

### ISSUE THREAD

**Issue by Hounk** [farin/JCloisterZone#183]
In a game with Halfling, he put the CCFF splitter tile with volcano to a city with his builder. But he did not get the bonus turn for it.

**Comment by farin** [comment]
@Hounk Halfling?

**Comment by Hounk** [comment]
Sorry, this was, as Uma Thurman in Pulp Fiction would have said, a little more information, than you needed.

"Halfling" is the nickname of the person, I played with, hence I wrote he placed the tile. But of course, this was totally irrelevant to describe the situation. So, no, there were no halfling tiles involved, as there are currently no halflings in JCZ anyway.

**Comment by farin** [comment]
I see :-)

**Comment by farin** [comment]
Just tried your scenario and works as expected.
Can't be possible it was alredy second builder turn?
Anyway without saved game can't do more now.
