### ISSUE TITLE
Incorrect counting of points

### ISSUE THREAD

**Issue by michalswierczynski** [farin/JCloisterZone#198]
With the final countdown, the rider blue obtained 17 points for the incomplete city and should get 18 points. Most likely not added him to the point where it stands pawn red.
13 x tiles + 5 x tiles with shield = 18 points
![carcassonne](https://cloud.githubusercontent.com/assets/13164883/11609612/a450db1c-9b8b-11e5-832e-9d1ffe997fa7.jpg)

**Comment by fatsu** [comment]
Scoring is correct: 12 tiles + 5 shields = 17 points.

You probably counted the tile right of the red meeple twice.

**Comment by michalswierczynski** [comment]
Yes I counted this tile twice.
So I played my boxed version of the wrong counting of the city. Thank you for a good lesson.
