### ISSUE TITLE
network auto discovery (former Awesome work!)

### ISSUE THREAD

**Issue by HughP** [farin/JCloisterZone#203]
I want to say this is some awesome work! I am really impressed.

FYI: I am running OS X 10.9.5 and it works well. My wife is running 10.7.x and we both downloaded the .zip and ran the application, put in our local network IP address and were able to start a game. It took me a minute to think about how to get the computers to see each other on the same network (LAN). But once I thought to use the IP address things got rolling.  

Just wondering if there was another way which is suggested to "auto find" another computer on the LAN? In OS X we have [Zero-config IP](https://en.wikipedia.org/wiki/Zero-configuration_networking), which Apple uses in its OS to show the computers in the network around you. I was expecting the available computers to show up. But I guess if we think about a solution which is cross-platform, maybe not all OSes support this? Anyway, I see windows and linux machines on my network, so maybe it is just JCloisterZone. There is a [mDNSResponder for OS X which interfaces with JAVA](http://www.macdevcenter.com/pub/a/mac/2004/08/31/osx_java.html).

More about Zero Config: http://www.zeroconf.org/

Also is there a way to export a screenshot of the current layout of tiles during game play?

Also does anyone know of an equal quality Catan game?

**Comment by farin** [comment]
Hi there is no "auto find" feature now. For non-power users there is "play online". I know it's not same, but at least you should be able connect without configuring anything
