### ISSUE TITLE
Link to playing instructions

### ISSUE THREAD

**Issue by HughP** [farin/JCloisterZone#204]
Some of the expansions listed in this game are new to me. I did not know the rules in how the pieces played. There seems to be no way within the game to look up the rules or which pieces are in the expansion. It would probably take a bit of work to build a link for each expansion and display the tiles in a window along side the rules for that expansion.
To solve my immediate problem, I used Google to find most of the rules for the expansions I was unfamiliar with. From what I understand Christopher Ober maintains a really nice PDF with this kind of data in it. I am not sure what license he puts on the work, as none was really visible. I am not sure how he maintains the data either - it sorta looks like he might use pages on OS X (as apposed to a markdown file which might be maintained on github and ingested into JCZ). But minimally a link to his latest version of the rule book might be suggested.

![jcloisterzone-recommendations](https://cloud.githubusercontent.com/assets/40230/12373752/f1b38470-bc49-11e5-97d0-49b87a1b4563.jpg)

**Comment by farin** [comment]
Yeah there can be link to http://www.carcassonnecentral.com/community/index.php?topic=60.0

**Comment by meepledrone** [comment]
You can include links to rules linking to WICA. You have access C1 and C2 rules with a finer grain than a link to the full CAR document. If needed, we could add additional info on the variants available on JCZ as required. You name it.

**Comment by farin** [comment]
5.x contains link to wikicarpedia
