### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by farin** [farin/JCloisterZone#206]
A request - could JCZ support a full screen mode?

This would be similar to the full screen mode many browsers support.  It would eliminate all borders, including that at the top, and allow the playing surface to go to the edge of the screen.  Scores, etc, would remain where they are.

This would be an advantage when playing on smaller or lower resolution screen.

thanks!

http://www.carcassonnecentral.com/community/index.php?topic=2293.0

**Comment by wTendera** [comment]
https://github.com/farin/JCloisterZone/pull/210

**Comment by Hueristic** [comment]
Very nice, Bet this was fun "bug-java-swing-key-bindings-lose-function-with-jdk-7-in-osx-with-awt-setfullscr" to find.
