### ISSUE TITLE
Scoring of the CCCC tile with pennant and tower base

### ISSUE THREAD

**Issue by joti** [farin/JCloisterZone#219]
I think the implemetation of the CCCC tile with pennant and tower base is wrong. The scoring works as if the pennant wasn't there. See the attached screenshot.

![nopennantscore](https://cloud.githubusercontent.com/assets/10690151/16709738/795f0a26-4619-11e6-8330-4fe4b9d22153.jpg)

**Comment by Alucard648** [comment]
Yes, the purple player should get 5 points for this unfinished castle (4 for tiles and 1 for pennant). Apparently pennant was missed in scoring.
