### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by HughP** [farin/JCloisterZone#225]
greetings, I am having a problem cloning this repo. Other repos no problem. Using Ubuntu 16.04.

Any suggestions welcome.

`git clone https://github.com/farin/JCloisterZone.git
Cloning into 'JCloisterZone'...
remote: Counting objects: 17416, done.
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed`

**Comment by farin** [comment]
@HughP it's question rather for GitHub and not me. Seems like some temporary GH error
