### ISSUE TITLE
Connection problems 

### ISSUE THREAD

**Issue by B1tchFight** [farin/JCloisterZone#226]
When my girlfriend tries to go online with JCZ she gets a error msg. If she set her client to German it said in English "Address family not supported by protocol family" if she is running it in English the error msg is different "Connection timed out"  With this info I checked the usual things like firewall, antivir(she reinstalled days ago so she doesn't have one)  We tried cable and wireless and I also checked the network setting they are equal to mine. And here it runs on Laptop and PC.  The only thing we couldn't test was port forwarding because she is in the Net at her fathers place. (this is why we want to play) When I checked the firewall settings Java was blocked first. I added the port for UDP and TCP and allowed java the connection. Restarted the system and it's still not working.

Any ideas? I am firm with PC tech. Means it's not a problem to chance certain settings or reinstall missing stuff. ;-)

**Comment by farin** [comment]
If you run it from console you should be able see full stack trace. That can halps
