### ISSUE TITLE
Java exception

### ISSUE THREAD

**Issue by Ulrick75** [farin/JCloisterZone#232]
Hello 
I just moved from v3.4.2 to 3.4.3.
When launching the application now I get a "A Java Exception has occurred".
Thanks for your great work.

**Comment by farin** [comment]
3.4.3. requires Java 8 (which is now updated on website)
My quess is that it can be reason

**Comment by Ulrick75** [comment]
...and your guess is correct!
I did not expect that a "minor" update (from v3.4.2 to 3.4.3) required a different compiler version, but thanks for your fast support nonetheless!
And thanks for your impressive implementation of the game.
