### ISSUE TITLE
Adjust Meeple Count

### ISSUE THREAD

**Issue by Decar** [farin/JCloisterZone#246]
I've just created a tile definition for the new Carcassonne For Two spin-off.  However the game is played with only 5 regular meeple.

It looks like the Meeple Count is hardcoded to load the 7 SmallFollowers when the initial GameStateBuilder is created.

Essentially, I'm looking for a way to get 5 meeple, mechanism for selecting the meeple count(along with the rules) would be a nice addition.

I can't see a YAML variable it.

I wonder if each expansion should have a corresponding definition document with capabilities and meeple counts. Carcassonne For Two could be implemented alongside a plugin.

I wondered if a Capability (java file) could be added to remove meeple, but I'm not confident how those could be loaded as a plugin.

Alternatively, there may be another sneaky way?

**Comment by farin** [comment]
Let me think about it little bit :) It's easier to add something then remove it. It's little bit unusual situation.

Tile count can be extracted to global yaml, but it's not much convenient. 

btw Could you provide link to  Carcassonne For Two spin-off please. I am wonder how it is differ.

**Comment by farin** [comment]
now there is no way to add capability as plugin, but technically it's not big deal. 
But in reality some expansions usually provides new game mechanic which are implemented as 
Phase instance. And adding new phase is now not possible because there is hardcoded phase graph.

**Comment by Decar** [comment]
Thanks for the reply Farin,

I understanding, writing a pluggable state-machine is quite a challenge!
Even if someone writes a new mechanic, what sequence do they occur in and
how do they interact!
It's a nightmare for sure!

Here's we're we discuss the new expansion.  I've done the tile distribution:

http://www.carcassonnecentral.com/community/index.php?topic=3444.0

and BGG:

https://boardgamegeek.com/boardgame/230751/carcassonne-fur-2

**Comment by farin** [comment]
Technically, it's not classical expansion. On the other hand it behaves just like different basic set.
What I can easily make (and I am going to include it in 4.0)
- change Expansion class from enum to plain class -> it allows creating new Expansion instance (eg by plugin)
- similary change Rule to class 
- add new StandardGameCapability, which defines small followers (so then small follower count can be replaced by providing different capability)
- then I am going to change little bit plugin definition to allow provided not only graphics but also brings new classes

this should be enough
only open question is how to display it on UI. I can probably just show all loaded expansions.

**Comment by farin** [comment]
Plugin move into https://github.com/farin/JCloisterZone-plugins
