### ISSUE TITLE
Return small city rule option (only 2 points for a small city)

### ISSUE THREAD

**Issue by Eldenroot** [farin/JCloisterZone#250]
https://www.carcassonneforum.cz/thread-494-post-11317.html#pid11317

**Comment by farin** [comment]
intentionally removed.
Disputed was open in carcassonnecentral.com thread.

**Comment by Eldenroot** [comment]
Why removed? :( Will be added back?

**Comment by farin** [comment]
As annotated rules says: "Note that the so-called ‘small city’ rule is no longer used in any edition"
Which means that Carcassonne from any publisher nowdays scores small city for 4 pts.
But because there is still group of people playing with legacy rules, it's still open to return in  back in 4.1

**Comment by Eldenroot** [comment]
> But because there is still group of people playing with legacy rules, it's still open to return in back in 4.1

Great, so we will be waiting for v4.1.0 then, because we use this rule for our tournaments...

**Comment by EvsanDlg** [comment]
It is v4.3.0 already but this rule is still not returned. Please, add this feature

**Comment by Eldenroot** [comment]
Yeah, missing :(

**Comment by farin** [comment]
Plugin would be way to go (to make legacy user happy and not spoil ui with legacy options)

**Comment by farin** [comment]
it's back 165de0a2ea84480f8b29f1628cf1221a604f53ff
