### ISSUE TITLE
Error while compilation

### ISSUE THREAD

**Issue by dmiszkiewicz** [farin/JCloisterZone#254]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project jcloisterzone: Compilation failure
[ERROR] /Users/dmiszkiewicz/Documents/git/JCloisterZone/src/main/java/com/jcloisterzone/game/capability/FairyCapability.java:[38,81] incompatible types: inference variable K has incompatible bounds
[ERROR]     equality constraints: com.jcloisterzone.figure.Follower
[ERROR]     lower bounds: com.jcloisterzone.figure.Meeple

**Comment by farin** [comment]
If you compile with maven, run it two times. 

Anyway I am going to remove this problematic type inference.

**Comment by oldherl** [comment]
Same error when compiling with maven.
Can't resolve even if run twice.
