### ISSUE TITLE
Abbey tile does not score completed city

### ISSUE THREAD

**Issue by uiuiko42** [farin/JCloisterZone#255]
Just tried version 4.1.0 for the first time.  A city was completed by playing an Abbey tile (see attachment) but the Abbey tile did not cause the city to be scored; nothing could be done with it for the rest of the game.  The abbey tile was the last tile played in the city.  This completely changed the final scores.

![abbey city](https://user-images.githubusercontent.com/35150939/34627810-0de2d894-f230-11e7-919c-429f34cff6ae.png)

**Comment by farin** [comment]
You probably don't have game saved after it happened. did you?

**Comment by uiuiko42** [comment]
No, I'm sorry.  Didn't save it.  If it happens again, I will.

**Comment by farin** [comment]
Fixed with aee653ef1656b47af891c1abdf85618a61fad2f6
(bug happening when two or more  sides touching abbey)

Milestone: 4.1.2
