### ISSUE TITLE
Error message "invalid placement"

### ISSUE THREAD

**Issue by uiuiko42** [farin/JCloisterZone#256]
Just tried version 4.1.0.  Near the end of the game, an error message appeared over the bar at the top showing the history of tile placements.  Screen shot is attached.

**Comment by uiuiko42** [comment]
Forgot to attach screen shot:
![carc error](https://user-images.githubusercontent.com/35150939/34627962-ac7c5b74-f230-11e7-844f-40bfa303b4de.png)

**Comment by farin** [comment]
Could you please try to play with 
http://jcloisterzone.com/builds/JCloisterZone-4.1.X.7z
for a while.

It's 4.1.0 repacked with old version of networking library (used in 3.x), nothing else.
So it should be conclusive if problem is there or not. I still suspect current network lib from losing message sometimes

**Comment by farin** [comment]
Any information about 4.1.X is useful. Both errors happening or not is good to know.

**Comment by uiuiko42** [comment]
Hi.  The friend I was playing did save the game.  I'm attaching it here;
hope it helps.

**Comment by farin** [comment]
Should be resolved by 4.1.1
