### ISSUE TITLE
Once barn is placed, farm hint colour returns to grey

### ISSUE THREAD

**Issue by DurbsUK** [farin/JCloisterZone#257]
Hi Farin, 

Not sure how to replicate, but played a couple of games of 4.0.2 recently with following errors related to the Barn.

1) Once barn is placed, farm hint colour returns to grey
2) On recent game, the barn has been auto-placed (in an illegal space), on one occasion when trying to select pig. Scored for one player, but not the other, i.e. showed to me like P2 had played barn, but P2 still had it available. Various errors, including "Farm is not occupied by follower". Can send save file if useful?
I can't see the barn being played in the save file, assume meepleID is "Barn"?

**Comment by farin** [comment]
changing title to just color issue, because point 2 will be solved by 4.1.1 
by Java-websocket library revert
