### ISSUE TITLE
Can't complete anything nearby castle having cart in it.

### ISSUE THREAD

**Issue by x-iso** [farin/JCloisterZone#262]
I've encountered this bug while playing with friends. not sure if it is related to cart used in castle, but most likely.
![inkednatsuo_x iso_alwi_20180302-044115_li](https://user-images.githubusercontent.com/13594634/36935520-bce5dd86-1f09-11e8-9dca-7f72b267083f.jpg)

**Comment by farin** [comment]
Next time, please save game after anything happen and provide it with report.
It really helps me. It can be replayed (even replayed in fixed version and validate it behave correctly)
It also contains order of play, sequence of drawn tiles etc ... this which can be  hardly decoded from just screenshot

**Comment by x-iso** [comment]
here are few savegames from that match, notice that in dfb.jcz last action is the tile placement that we could not acheive and even though for some reason in this save game it's placed, the town is not scored, and meeples stay in their positions.
[saves.zip](https://github.com/farin/JCloisterZone/files/1783057/saves.zip)

**Comment by x-iso** [comment]
[WXWXWXW.zip](https://github.com/farin/JCloisterZone/files/1869757/WXWXWXW.zip)
here's another issue encounter, forgot about this problem and got stuck again. could you help explain how to edit save in a way that would allow to swap the cart with normal meeple that is used on other feature?
