### ISSUE TITLE
Flying machines add-on bug when using undo.

### ISSUE THREAD

**Issue by x-iso** [farin/JCloisterZone#263]
if flying machine is used then dice is rolled and meeple is placed, using Undo will corrupt the game as it will return the meeple, but nothing can be done anymore. Using undo after dice is rolled (or any random is generated) should be prohibited in any add-on.

**Comment by farin** [comment]
Prohibit undo after dice roll / tile draw etc is my intention. (and probably this cause game corruption because it's prohibited on some level, but unfortunately not reflected in UI )
