### ISSUE TITLE
Trivial - BUILDING.md directs to JDK 8

### ISSUE THREAD

**Issue by Decar** [farin/JCloisterZone#264]
Code no longer runs under JDK 8.  
Loading a saved game the VM fails because ByteBuffer.flip() doesn't exist.  
JDK 9 resolved this issue because the method exists.
Here's a URL:
http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html

**Comment by farin** [comment]
Buffer.flip should be there since https://docs.oracle.com/javase/7/docs/api/java/nio/Buffer.html#flip()

Last time I run it. I used 
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by Decar** [comment]
Actually, forgive me...I've not installed Java for so long I'd not realised
what happened.
I'd installed the Java 10 SDK, but compiled it as JDK 8:

This was the error I saw, and explanation:
https://github.com/plasma-umass/doppio/issues/497#issuecomment-334740243

I deleted 10 and installed with 9 and configured eclipse to compile and run
as 9.

Feel free to close this....I'm feeling old now.... Java 10, I first used
1.1 ;(
