### ISSUE TITLE
NullPointerException when expanding "weird" city

### ISSUE THREAD

**Issue by joti** [farin/JCloisterZone#280]
When I placed a tile next to one of the "weird" city tiles of the Hills & Sheep expansion, the game suddenly crashed with NullPointerException.
![NullPointer_HaS](https://user-images.githubusercontent.com/10690151/57047854-85e59d00-6c72-11e9-8634-2a1c39ac27e7.jpg)
[NullPointer_HaS_error.log](https://github.com/farin/JCloisterZone/files/3136222/NullPointer_HaS_error.log)

**Comment by farin** [comment]
duplicated by #306 and fixed
