### ISSUE TITLE
Website: https doesn't work properly

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [farin/JCloisterZone#289]
If I open the website through a link (jcloisterzone.com/en/) from a search engine (DuckDuckGo), there is no https/TLS.
If I force https with HTTPS Everythere or through typing https:// in the address bar, there is the error message SSL_ERROR_BAD_CERT_DOMAIN: "Websites confirm their identity by means of certificates. Firefox does not trust this website because the certificate used by the website is not valid for jcloisterzone.com. The certificate is only valid for the following names: *.gitlab.io, gitlab.io" (Translated from German).
If I use the main download link from the webpage (https://play.jcloisterzone.com/builds/JCloisterZone-4.4.1.7z), there is a  MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT-error.
Because this is an download server, in my opinion it is even more important to have an encrypted connection.

**Comment by farin** [comment]
moved under a new provider with proper HTTPS certifcates
