### ISSUE TITLE
Preset saving does not work

### ISSUE THREAD

**Issue by gagarski** [farin/JCloisterZone#29]
Steps to reproduce:
1. Start a new game
2. Check some expansion checkboxes
3. Enter preset name and click "Save"
4. Start the game, put some tiles and exit (or play till the end)
5. Restart JCloisterZone
6. Try to create a game from preset

Expected results:
1. Saved preset in presets list
2. Saved preset in config.yaml

Observed result: 
neither of expected results

**Comment by farin** [comment]
probably linked with readonly game folder - #79
