### ISSUE TITLE
Please provide an installer for Windows to make JCloisterZone installation more user-friendly

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [farin/JCloisterZone#293]
I tried to play JCloisterZone with a friend who uses Windows. I had to explain how to install and run it over the phone and it was very complicated, because on Windows you have to install Java and an extractor for the .7z-file first, extract these file and then you can run it, but not via a normal desktop icon or a start menu entry; instead of that you have to go to the folder where you have extracted the data and click at the .jar file. It took half an hour until it was installed and working.
This shows that the lag of an installer makes the installation JCloisterZone not very user-friendly.
For me, that is not a problem, but for less tech-savvy persons it is.

It would be great if you could deploy a simple installation file which take care of the installation of Java - if necessary - and extracts the data to the standard program folder of Windows and creates shortcuts on the desktop and in the start menu, if desired.

Normally, as a Linux user, I would not care much about how to install a software on Windows; but if you want to use it with other persons who use different operating systems and have different knowledge, it gets important.

**Comment by java-py-c-cpp-js** [comment]
I have made some research on my own and managed to build an installer for Windows myself: https://github.com/java-py-c-cpp-js/Installer4JCloisterZone
Currently, I only have uploaded the configuration files, but if you allow me to do that, I could also upload a build of the Installer4JCloisterZone_4.4.1.exe file.

**Comment by farin** [comment]
this will be inevitable as I merge Java FX branch

**Comment by java-py-c-cpp-js** [comment]
> `this will be inevitable as I merge Java FX branch`
Do you mean it is inevitable to provide an installer yourself or it is inevitable for me to upload the Installer4JCloisterZone_4.4.1.exe to the corresponding repo?

**Comment by farin** [comment]
to provide installer 
In fact it will be needed to provide platform specific build, which is option also to pack it 
as executable

**Comment by java-py-c-cpp-js** [comment]
Ok, that sound good (not that it is necessary to provide platform specific builds, but that there will be (an) installer(s) ;-)

**Comment by java-py-c-cpp-js** [comment]
I suggest to keep this issue open until an installer for Windows is provided.

**Comment by java-py-c-cpp-js** [comment]
Can you estimate when merging the fx branch and creating the installation packages will be ready? If it will take some time, I would ask to upload my installer on my repo so friends of me can easily download and use it. I would include a warning that it is not an official installation packages and that it will be deprecated soon.

**Comment by farin** [comment]
It definitely takes same time. (weeks at least)
I made some eperiements with combining Java FX and old Swing. Although it can be combined it leads to visial artefacts. So now I think the way is convert all views to FX. Using old Swing is not option in long term, FX is much easier to maintain and develop and I don't want to invest to Swing branch.

**Comment by java-py-c-cpp-js** [comment]
So it indeed would make sense to upload the installer. Can I do that? (I know that this would be allowed by the license of JCloisterZone, but I want to be polite and ask)

**Comment by farin** [comment]
Of cource. Do it then I can link your unofficial installer from homepage.

**Comment by java-py-c-cpp-js** [comment]
Ok, I've managed to make a "release" of the installation software: https://github.com/java-py-c-cpp-js/Installer4JCloisterZone/releases/tag/v0.1

**Comment by farin** [comment]
Done

**Comment by java-py-c-cpp-js** [comment]
Thank you :-)
