### ISSUE TITLE
Error on MacBook Air

### ISSUE THREAD

**Issue by DmytroKharchenko** [farin/JCloisterZone#294]
Hi! Downloaded latest Java (8u241) but the Game does not work. Picture of error.log is attached
![Снимок экрана 2020-03-30 в 21 10 07](https://user-images.githubusercontent.com/62903738/77946467-0372bc80-72cb-11ea-8011-e79d39f521eb.png)

**Comment by farin** [comment]
note for myself: it's possible that apple classes are excluded by shade-plugin and minimize plugin

Quick workaround can be 
downloading 
https://repo1.maven.org/maven2/com/apple/AppleJavaExtensions/1.4/AppleJavaExtensions-1.4.jar

and running (with downloaded jar in same folder) as
`java -jar JCloisterZone.jar -cp AppleJavaExtensions-1.4.jar`

**Comment by matejmatoulek** [comment]
I got the same error as @DmytroKharchenko. When I tried to use your workaround I got this:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jcloisterzone/ui/JCloisterZone : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)`

**Comment by farin** [comment]
@matejmatoulek  are you running it with java 8 (try java --version)
(because error message is saying you are using java < 8)

**Comment by matejmatoulek** [comment]
Yes, you were right. I was on some really old Java version. Now I'm fine:
`java version "14" 2020-03-17`

But I'm getting another error message:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/ApplicationListener
	at com.jcloisterzone.ui.JCloisterZone.run(JCloisterZone.java:252)
	at com.jcloisterzone.ui.JCloisterZone.main(JCloisterZone.java:278)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
`

**Comment by farin** [comment]
ok, let me rebuild it today and provide a build which will be hopefully working for you
If it will be ok I am going to relase it as official build

**Comment by DmytroKharchenko** [comment]
Hi! Yes, please share the new build. Got the same (I guess) error as @matejmatoulek 
![Снимок экрана 2020-04-01 в 20 31 02](https://user-images.githubusercontent.com/62903738/78167897-e61f2900-7457-11ea-9ea7-da87f00deb6f.png)

**Comment by farin** [comment]
workaround build until fixed properly
https://drive.google.com/file/d/1ykSRvuGFJS_t4sZnFv2zlf0ui9i9hl0V/view?usp=drive_web

**Comment by DmytroKharchenko** [comment]
> workaround build until fixed properly
> https://drive.google.com/file/d/1ykSRvuGFJS_t4sZnFv2zlf0ui9i9hl0V/view?usp=drive_web

Great! It works! Thanks a lot!

**Comment by DmytroKharchenko** [comment]
@farin Another issue appeared with the version on GoodDrive:
Last login: Fri Apr  3 23:04:02 on console
Dmitrys-MacBook-Air:~ Kharchenko$ java -jar /Users/Kharchenko/Downloads/JCloisterZone-1/JCloisterZone.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jcloisterzone.ui.Client (file:/Users/Kharchenko/Downloads/JCloisterZone-1/JCloisterZone.jar) to method com.apple.eawt.FullScreenUtilities.setWindowCanFullScreen(java.awt.Window,boolean)
WARNING: Please consider reporting this to the maintainers of com.jcloisterzone.ui.Client
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Thread-15] WARN com.jcloisterzone.ui.ClientMessageListener - No controller for message CLIENT_UPDATE

**Comment by farin** [comment]
This can be also hacked by custom build.

**Comment by DmytroKharchenko** [comment]
Which build? The new expected one?

**Comment by farin** [comment]
@DmytroKharchenko sorry, it wasn't clear, I can made another build which excludes all apple specific stuff (which probably makes trouble with some OSX versions]. Tomorrow

**Comment by DmytroKharchenko** [comment]
@farin thanks a lot! Will really appreciate it!

**Comment by farin** [comment]
@DmytroKharchenko just one question, is it causing anything fatal or is it just warning in console?

**Comment by DmytroKharchenko** [comment]
@farin it seems 1st one as it does not let the game to be launched

**Comment by farin** [comment]
@DmytroKharchenko could you try this http://play.jcloisterzone.com/builds/JCloisterZone-4.4.2.7z

**Comment by DmytroKharchenko** [comment]
@farin Thanks a lot! Just tested - seems everything works!
