### ISSUE TITLE
Search game

### ISSUE THREAD

**Issue by KrzysztofMadejski** [farin/JCloisterZone#296]
There are so many games on the server, it would be great if there was a filter box to search for the right one.

**Comment by Nickyes** [comment]
i saw also that the scroll in game list is a little weird... scrolls in a slow mode, and sometimes neither the scrollbar "drag-and-dropped" with the mouse can reveals those games at the end of the list... so sometimes it is not possible to join that games

**Comment by farin** [comment]
don't worry, I just deployed new website + player server with fixed zombie games will following this in  or days. Only need to test it properly.

**Comment by Nickyes** [comment]
Great!!! Thanks a lot

**Comment by farin** [comment]
Server was upgrade.
