### ISSUE TITLE
[Thread-1] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException

### ISSUE THREAD

**Issue by KrzysztofMadejski** [farin/JCloisterZone#297]
Which is a non-blocking error, but games takes a lot of time to catchup after other online players moves.

**Comment by farin** [comment]
can't verify / fix without stack trace

**Comment by KrzysztofMadejski** [comment]
@farin I'd love to provide stack trace, but there was none. Just this one line. I'd verify the code to check if in all places where exceptions are caught and not passed further the stacktrace is printed to error log.
Does `logger(e.getMessage(), e)` logs stack trace? Shouldn't logformat be changed in logger properties, sth such as `org.slf4j.simpleLogger.format=[%1$tc] %4$s: %2$s - %5$s %6$s%n %7$s` ?

**Comment by farin** [comment]
Hopefully this is fixed in 4.5.0
