### ISSUE TITLE
License of tiles

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [farin/JCloisterZone#299]
Where did you get the images of the tiles? Are they also licensed under the AGPL license?

**Comment by farin** [comment]
No

**Comment by java-py-c-cpp-js** [comment]
Do they have an other open source license?

**Comment by farin** [comment]
I don't think so.

**Comment by farin** [comment]
Honestly clean way to do this would be distribute classic.jar plugin separately and bundle generic tiles instead as defaults.
