### ISSUE TITLE
Doesn't let you place your tile

### ISSUE THREAD

**Issue by noelicus** [farin/JCloisterZone#3]
Hi, sometimes JCloister doesn't let you place your tile - you move the tile to one of the valid positions (and they're marked with a dark line) and you can't place the tile. I have definitely seen this where it gets confused about the bonus due to the builder, and I may have seen it at other times. Usually, but not always, it seems to only half believe it's your go: the triangle on the right points to your name, but the "valid position" squares are not black, but the darker grey you notice when it's not your go.

Love the game. Thank you!

**Comment by brasey** [comment]
I don't believe it is OK. Tried to play multiplayer, can't place the first tile. Was able to play single player.

Version 3.2.0 on Fedora 21
$ java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b13)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by farin** [comment]
@brasey do you play on play server or with direct connection?
What exactly mean "can't place the first tile" ? 
Are you able to place with another click or are you unable to place at all. Just for sure, are you active player?

**Comment by brasey** [comment]
A friend started a game on our LAN. I connected to his server just fine.
He moved first. Placed his tile with no problem.
Turn passed to me. I could see available placement for my tile.
Left-click on highlighted squares multiple times... nothing happens.

HTH

**Comment by farin** [comment]
@brasey thx, btw could you look if error.log was created in game folder?

**Comment by brasey** [comment]
just this, but I think it's from a first connection attempt before my friend had the game server running:

```
[AWT-EventQueue-0] WARN com.jcloisterzone.ui.GameController - Subscriber not registered.
[AWT-EventQueue-0] WARN com.jcloisterzone.ui.GameController - Subscriber not registered.
[AWT-EventQueue-0] WARN com.jcloisterzone.ui.GameController - Subscriber not registered.
[Thread-15] ERROR com.jcloisterzone.ui.Client - Connection refused
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.Socket.connect(Socket.java:589)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:166)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by farin** [comment]
@brasey btw if you have time it would be fine try if chat is working or not (it helps me better focus to right place - because it shows if it is general connection issue or something more specific to placement only.

**Comment by brasey** [comment]
I am able to start a game and have someone join, and to play a game (and chat).

I won't be able to test connecting to someone else's game until tomorrow. I'll test chat then and post here.

**Comment by farin** [comment]
should not happening with 4.x versions
