### ISSUE TITLE
Discarded River tiles could have been played

### ISSUE THREAD

**Issue by Onatrum** [farin/JCloisterZone#300]
Using the River and River II expansions, the game discarded tiles which could have been played at the beginning of the game.  

The AI had placed a river w/city tile near the other river. The remaining river tiles were discarded after the first river was completed.  However, at least two of the river tiles could have been played that would have connected to the city and continued the river.

- First attachment is a screenshot of the game.
- Second attachment is the saved game (zip file), if it helps at all.
 
**EDIT...based on replies that I've gotten, it seems that the original screenshot I uploaded (taken after the game had ended) was misleading people into not seeing the issue.  I have edited the screenshot and reattached so it more accurately resembles the issue as it occurred in the beginning of the game.**

![Possible_bug_2](https://user-images.githubusercontent.com/63882078/79672634-ec284000-81a1-11ea-8c6f-374c6815ccdb.png)
[Possible bug.zip](https://github.com/farin/JCloisterZone/files/4495404/Possible.bug.zip)

**Comment by Alucard648** [comment]
Not a bug, as I can see. Roads are culprit here.

**Comment by Onatrum** [comment]
The original screenshot I uploaded was taken at the end of the game, and may have masked the issue I'm submitting.

I have updated the original screenshot to more accurately display the board is it appeared at the beginning of the game, when the issue occurred.


    On Saturday, April 18, 2020, 12:06:39 AM EDT, Alucard648 <notifications@github.com> wrote:  
 
 


Not a bug, as I can see. Roads are culprit here.

**Comment by farin** [comment]
yeah in this case it make sense to place it instead of discard
but it's hard to define it with exact rule
game is now following "completed annotated rules" which disallows placement rivers to close. Including touching by corners (this case)

**Comment by Onatrum** [comment]
> 
> 
> yeah in this case it make sense to place it instead of discard
> but it's hard to define it with exact rule
> game is now following "completed annotated rules" which disallows placement rivers to close. Including touching by corners (this case)

This is a good point.  

If the tile(s) cannot be played due to rules specific to the River/River II expansions, then this may be more of a "bug" with the rules than the program.  If that's the case, then this issue can be ignored since the program is functioning as expected.  

I'll leave it up to the creator/community to decide if this issue should be closed.  After a dozen or so games, I have not encountered this issue again.
