### ISSUE TITLE
Shepherds not scored in closed field

### ISSUE THREAD

**Issue by meepledrone** [farin/JCloisterZone#303]
Shepherds placed in a closed field are not automatically. See the attached file for a game with an example: a shepherd placed in a field was surrounded by a circular road. 

In general terms, when a field cannot be extended, the "Herd flock into the stable" action should be invoked automatically.

The same should happen if you place the shepherd in a inner field:
* You place the shepherd and invoke the "Expand the flock" action automatically.
* As the inner field cannot be extended, the "Herd flock into the stable" should be performed automatically. 

Please check the **Special case** and the associated footnotes here right before the example:
http://wikicarpedia.com/index.php/Hills_%26_Sheep_(1st_edition)#Shepherd_and_Sheep

[H&S_Shepherd_not_evaluated.jcz.zip](https://github.com/farin/JCloisterZone/files/4518505/H.S_Shepherd_not_evaluated.jcz.zip)

**Comment by farin** [comment]
duplicate to #281

**Comment by farin** [comment]
unfortunately this one is pretty complicated. It needs to newly track "closed" state on fields. 
But definitely, valid complain.

**Comment by meepledrone** [comment]
Sorry. I didn't see issue #281. 

Thanks!

**Comment by farin** [comment]
Fixed by https://github.com/farin/JCloisterZone/commit/269dbe2e4f252af951dbfe6e66b94eae01d7aa5e
