### ISSUE TITLE
Play Server is rejecting connections

### ISSUE THREAD

**Issue by meepledrone** [farin/JCloisterZone#309]
I hit "Play Online" on the initial JCZ screen. Then I enter my nickname and click "Connect", get the message "Connecting..." briefly and then JCZ goes back to the initial screen. Some times you can see the game list page for less than a second before you are sent back to the initial screen. This behavior happens on JCZ 4.4.1 and 4.4.2 on Mac OS.

I also tried on JCZ 4.3.2 and you get on the connection screen the following message displayed in red: "Connection failed. (No value present)" and stays on the same screen and it does not go back to the initial screen.

**Comment by farin** [comment]
redeployed and praying for it's already ok
