### ISSUE TITLE
Shepherd/Farmer on field

### ISSUE THREAD

**Issue by WGFizban** [farin/JCloisterZone#310]
Hi Farin! First of all, many thanks for the wonderful work on the Carcassone implementation project. 
I think I found a small bug in S&H. According to the instructions:
_"You can place your shepherd even if there is already a farmer
in that field (**and vice versa**), but you cannot place a
shepherd if there is already another shepherd in that field."_
And there is a problem. The blue player has a shepherd in the field. A few tiles later add a tile so that he could put a farmer there ... but he can't. I attach a photo with the problem.

![image](https://user-images.githubusercontent.com/63311150/80317520-989e9d80-8804-11ea-96d7-3c51c428cf55.png)

**Comment by farin** [comment]
https://github.com/farin/JCloisterZone/issues/305

Should be released in couple days
