### ISSUE TITLE
Load savegame.jcz in multiplayer online

### ISSUE THREAD

**Issue by Nickyes** [farin/JCloisterZone#311]
Please, can you add the possibility to load and play saved .jcz files also in multiplayer?

As always, thanks a lot

**Comment by farin** [comment]
@Nickyes it's possible. Just load your game and let other to join when page with expansions is open. Just like when you creating a new game.

**Comment by Nickyes** [comment]
ehm... you mean also if we play in public server?

**Comment by farin** [comment]
public server is different story, there is no "load", but anyone can continue a game he participated before 
(as long as his clientId and secret in config remains unchanged)

(well there as some issues with reconnecting to game but this should be now ok)

**Comment by Nickyes** [comment]
yes, with games played in a public server, I can continue a game... but only if I controll all the other players, it isn't?

**Comment by farin** [comment]
no, on public server players are still assigned to original clientId. You can control only your own players. 
Did you share you config with others? Because in such case, all parties will be use same clientId and after reconnect all offline player will be assigned to a new session.
It's good idea keep clientId/secret unique for all players.

**Comment by Nickyes** [comment]
My only purpose is to end with my friends some multiplayer games in the public server that arrested for some errors (that you said that are now fixed)... so i wanted to load my backup files and tell to my friends to re-connect to that session to finish.

**Comment by farin** [comment]
@Nickyes unfortunately that's not easily possible. You can arrange direct connection and load game here.

**Comment by Nickyes** [comment]
ok thanks... i did not found how to do, but ok. 
Can be possible that my provider disabled this service?

**Comment by farin** [comment]
@Nickyes you need public IP address (which is often not true) or use tunnel (eg Hamachi VPN)

**Comment by Nickyes** [comment]
very kind... i know hamachi only for name, i will investigate
thanks
