### ISSUE TITLE
Shepherds on the field at the end of the game are not scored

### ISSUE THREAD

**Issue by meepledrone** [farin/JCloisterZone#314]
Shepherds in a field at the end of the game are not scored

Tested version 4.5.0

Please find saved game and screenshot (check for red shepherd near bottom)

[H&S_I&C_Shepherd not evaluated after the game 6.jcz.zip](https://github.com/farin/JCloisterZone/files/4563573/H.S_I.C_Shepherd.not.evaluated.after.the.game.6.jcz.zip)

![Screenshot 6](https://user-images.githubusercontent.com/64163262/80799843-33520000-8ba8-11ea-88b1-77291288d41f.png)

**Comment by farin** [comment]
rules saying 
if your shepherd and sheep are in a field at the end of the game, you do not score any points for them.

**Comment by meepledrone** [comment]
My bad. They score 0 points at the end of the game.
