### ISSUE TITLE
Leaving the game does not show initial screen

### ISSUE THREAD

**Issue by meepledrone** [farin/JCloisterZone#315]
Right after starting several games or even during a game, I pressed "Leave game." The game was ended but the screen displayed was still that of the game in progress. The menu, however, allowed me to start a new game normally. 

It is some kind a screen refresh issue, since I tried to take a screenshot but somehow, the file shown the initial screen and not what I'm seeing n the screen. When I switch to another window and back, the initial screen is show properly.

Tested version 4.5.0 on MacOS X 10.11 El Capitan

**Comment by farin** [comment]
added one explicit repaint. Reopen if issue remains for 4.5.1
