### ISSUE TITLE
JCloister 4.5.1 and 4.4.2 - Hills & Sheep - ERROR java.lang.IllegalStateException: Pass is not allowed

### ISSUE THREAD

**Issue by Ghost-RiOt** [farin/JCloisterZone#317]
Hi, we tried on JCloister 4.5.1 and 4.4.2 on an Online Game with Hills & Sheep, and when we chose to Expand or Herd the flock, we get this error message: "java.lang.IllegalStateException: Pass is not allowed".
At the same time, we this player got disconnected and it crash the game for everyone.

Here is the error report:
[error.log](https://github.com/farin/JCloisterZone/files/4567003/error.log)

Sorry did not have the saved game.

**Comment by Ghost-RiOt** [comment]
Just tried with local game without online player and with online player and it work as expected.
The only issue seems when we play on the JCloister Server.

**Comment by farin** [comment]
Thanks for a report. Server is now fixed, you can even continue with interrupted games if you still didn't remove it.
