### ISSUE TITLE
Castle scored in same turn it is created if other features completed as well

### ISSUE THREAD

**Issue by meepledrone** [farin/JCloisterZone#321]
A castle is scored in the same turn it is created if other features are also completed. As per the rules, the castle scoring can only be triggered on a later turn. 

Please find next two examples tested on v4.5.1:

Example 1: The tile marked in black completes a unoccupied 4-tile road and a small city that is converted into a castle. Unexpectedly the castle scores 4 points for the unoccupied completed road.

Example 2: The tile marked in black completes an unoccupied monastery and a castle. It also completes a city that is converted to a castle. The completed unoccupied monastery triggers the scoring of the exiting castle for 9 points but, unexpected, it also triggers the scoring of the newly created castle for 9 points too.

Please find the screen shots and the saved games:

**Example 1:**
![BC B_Example_01](https://user-images.githubusercontent.com/64163262/81417756-f52a8280-914b-11ea-9309-34d7f6a964c9.png)

**Example 2:**
![BC B_Example_02](https://user-images.githubusercontent.com/64163262/81417781-feb3ea80-914b-11ea-9907-ab690643b9fe.png)

[BC&B - Castle scored right after city conversion_Example_01.jcz.zip](https://github.com/farin/JCloisterZone/files/4599718/BC.B.-.Castle.scored.right.after.city.conversion_Example_01.jcz.zip)
[BC&B - Castle scored right after city conversion_Example_02.jcz.zip](https://github.com/farin/JCloisterZone/files/4599719/BC.B.-.Castle.scored.right.after.city.conversion_Example_02.jcz.zip)

**Comment by Nickyes** [comment]
in fact the complete annotated rules  vers. 7.3 (page 117 rule#368) says:
> The **RGG** version of the rules states that the castle scores only "when the first feature...in the 
> vicinity of the castle is **later** completed" (emphasis added) - while a subsequent turn is not specifically mentioned, it seems apparent in both rule sets that a feature that is completed on the turn that the castle is built does not allow the castle to score
