### ISSUE TITLE
could not find the main class problem

### ISSUE THREAD

**Issue by clintonwu2013** [farin/JCloisterZone#332]
hi when i click JCloisterZone.jar icon, it pops up the message  "could not find the main class....".
I do not know what is wrong because it used to be fine....
![pic](https://user-images.githubusercontent.com/50483339/84573472-34936100-add3-11ea-900f-90c0a076e017.png)

**Comment by clintonwu2013** [comment]
i have solved the issue by using command line "java -jar JCloisterZone.jar". But i think it is still weird that one cannot open the program by double clicking the icon. Maybe it due to the incompatibility with Windows 10?

**Comment by stanolacko** [comment]
Sometimes happend. But it's not problem of JCloiserZone, it is problem with your installation of Java.
