### ISSUE TITLE
Small problem with the ferries

### ISSUE THREAD

**Issue by WGFizban** [farin/JCloisterZone#333]
Hi Farin! 
I found a stupid mistake in the "ferries" extension. It concerns the attempt to position the ferry in the position it was in before. When it is the same item, the program generates an error. I think it should be easy to correct. Thanks
![error](https://user-images.githubusercontent.com/63311150/87253287-59363380-c47a-11ea-82d0-49549878fa7b.jpg)
[error.log](https://github.com/farin/JCloisterZone/files/4909051/error.log)

**Comment by farin** [comment]
won't fix old 4.x client, please upgrade to 5.x
