### ISSUE TITLE
Several online game issues

### ISSUE THREAD

**Issue by Nickyes** [farin/JCloisterZone#335]
in the past month was no more possible to play online games because one or more of these issues:

- too much time in waiting to start a game, someone or all members have to restart jcloisterzone few times in a row before online game playability get back

- most times (read: "all times"), games end after about no more of 20 moves. All members are knocked out the game and receive "the game doesn't exist" as error.

- only the current player are knocked out, but others view him as he is normally playing. Only if restart jcloisterzone they notice that the game is deleted from the list

We're waiting for the new update, hoping that with the new UI you can fix also this issues... that make impossible to play online

Thanks a lot

**Comment by farin** [comment]
looking at hosting and see there is 100% RAM usage
I am going to upgrade hosting plan and reboot all
stay tuned...

**Comment by farin** [comment]
you can try it now

**Comment by Nickyes** [comment]
thanks, we'll try and then let you know about

**Comment by Nickyes** [comment]
yes!!! Should be ok now! For the first time we started two games and finished! THANKS!

Note that in some moments the game had some restarts. But this little bug didn't condition the game...
