### ISSUE TITLE
Wagon C2 Rules

### ISSUE THREAD

**Issue by stanolacko** [farin/JCloisterZone#336]
Due to different rules for move of Wagon on C1 and C2 it will be good to allow user to play be selected rules.

C1: - wagon can move after finishing feature with wagon to any unoccupied unfinished but connected feature
C2: - wagon can move after finishing feature with wagon to any unoccupied unfinished feature on tile where wagon is located or on all tiles arround this tile (tile with wagon)

Current version follows C1 version of rules.

**Comment by farin** [comment]
Good point, I am currently working on big client update which includes C2 support (Abbot, Gardens etc.)
I will definitely include also this. Current estimate for all done is release during September.

**Comment by stanolacko** [comment]
Thanks!

**Comment by farin** [comment]
@stanolacko 
![image](https://user-images.githubusercontent.com/533295/90642119-48739d00-e232-11ea-840c-18e1f6ce4081.png)

**Comment by farin** [comment]
@stanolacko 
![image](https://user-images.githubusercontent.com/533295/90642234-6ccf7980-e232-11ea-9468-40824979c1f4.png)

**Comment by stanolacko** [comment]
Nice UX, as I wrote to mail to you, I want to participate on making plugins for standard game and expansions. Currently working on Wells expansion but currently I'm waiting for new game engine.
My idea is to create plugin with fan expansions without change of main game engine.

**Comment by farin** [comment]
@stanolacko could you ping me with email (I don't know now what is you email) We can provide you some estimations and give you more details

**Comment by stanolacko** [comment]
@farin Did you get my email?

**Comment by stanolacko** [comment]
Mistake ;-)

**Comment by farin** [comment]
@stanolacko no. Did you wrote to farin@farin.cz ?

**Comment by stanolacko** [comment]
Yop. Ok. I'll try different mail client and/or different mail account torrowe
