### ISSUE TITLE
Add tiles without rules

### ISSUE THREAD

**Issue by ajacfabian** [farin/JCloisterZone#339]
Hello, I'm a big fan of the game. I have a few questions.

1) If multiple expansions that have river beginnings and endings are selected, would it be possible to implement a feature to include all river sources at the beginning of the game as to have multiple rivers? Perhaps have it based on different sides of the Count of Carcassonne expansion.

2) I noticed that in issue 266 (additional playing options) you mentioned that it is possible to have the tower tiles without the tower rules by editing your config.yaml file. Is it possible to do this with other expansions? I'd like to have all of the tiles in the game but with the rules of a subset of them, ie, I'd like to play the Princess and Dragon tiles without the associated rules of that expansion.

Thank you,

-Adrien

**Comment by farin** [comment]
closing as 5.x client is now stable
