### ISSUE TITLE
Wrong points assigned on closing city

### ISSUE THREAD

**Issue by frapixel1987** [farin/JCloisterZone#340]
Hi Farin,
we were playing in 3 friends online on a game with password. The rules were: no farmers and with the "Inns & Cathedrals", "Traders & Builder" and "Hills & sheep" expansions.

We had this city: 
![JcloisterBug 1_LI](https://user-images.githubusercontent.com/20630919/91616854-dfed9400-e986-11ea-9caa-142bbc745e4b.jpg)

On it there were:
Yellow: One big meeple, one normal Meeple, builder 
Red:  One big meeple, one normal meeple, builder
Green: One big meeple

When the city was closed by Red, points were incorrectly calculated: only I (Yellow) took the points for the city, even if we shared the same number of Meeples. The resources were correctly assigned to Red, who closed the city. 
![JcloisterBug 2_LI](https://user-images.githubusercontent.com/20630919/91618473-b7679900-e98a-11ea-89d7-c2b9a780ea74.jpg)

At the link a recording of the portion of game when the bug occurs (precisely, at 2:34)
https://youtu.be/8cTrbbrMKxc

Thank You!
Francesco

**Comment by farin** [comment]
Do you have saved game? It's the most valuable for me to investigate it.

**Comment by frapixel1987** [comment]
Unfortunately no, we don't

**Comment by stanolacko** [comment]
Ok. @farin @frapixel1987: It is absolutely no bug.
You played also Hills and sheeps expansion.
Than Red and Yellow had a tie: eacho of then 1 standard meeple and 1 double meeple.
When tie than is checked if some of meeple is not on tile with Hill. 
And Yellow is on tile with hill.
So Yellow is winner in tie and get's all points.
So tell to friend who played Red color that sorry, it was by game rules.
![Snímka2](https://user-images.githubusercontent.com/1910456/91666640-ba839600-eafe-11ea-88d9-b04c78b59090.JPG)

**Comment by farin** [comment]
@stanolacko good catch. anyway it brings me idea for upcoming 5.x to indicate to players if tiebreaker rule was applied (and prevent such confusion)

**Comment by stanolacko** [comment]
Good idea.
I found it when checking why is different colors on some tiles and found that it's Hills and Sheeps and then I checked all city's tiles and there was the "problem".

**Comment by frapixel1987** [comment]
thank you @stanolacko for the explanation, we used the expansion only for the extra tiles and the bonuses to monasteries, we didn't know the this rule on ties.

**Comment by stanolacko** [comment]
@frapixel1987 understand, I spoke with farin and he told that he is inspired with this issue to show that was tie in this case and rules for tie was applied.
Anyway, check this rule http://wikicarpedia.com/index.php/Hills_%26_Sheep_(1st_edition)/en
Side effect of this expansion is that it use tiles which are put under tile with hill. So you don't know which one.
It's rule agains tile counter players ;-)
