### ISSUE TITLE
Versioning artworks

### ISSUE THREAD

**Issue by stanolacko** [farin/JCloisterZone#346]
When running Client first time, it check downloaded artworks.
When artwork not installed download and store it in installedArtworks.
But, when some new version of artwork will be published, engine will skip updating due to not check requested version of artworks defined by engine.
Anyway, meybe it will be good when artworks and tile definition will returning by Engine.jar, because currently tiles has to be defined in both Engine and Client separately in two different formats - possible bug/mistake place ;-)

**Comment by farin** [comment]
https://github.com/farin/JCloisterZone-Client/commit/1ae0052f0409fdbf1f0a353ebb91fb1fa954444e
