### ISSUE TITLE
More than 6 players?

### ISSUE THREAD

**Issue by Visagalis** [farin/JCloisterZone#347]
https://github.com/farin/JCloisterZone/blob/2428d6755ff12b8fa70deddb98c91f9ecc2b9a45/src/main/java/com/jcloisterzone/game/PlayerSlot.java#L39

Currently, there is hardcoded 6 max players what's the reason behind this limitation?

**Comment by farin** [comment]
Hi, in 5.x engine there is no limitation. And a new ui client https://github.com/farin/JCloisterZone-Client has 9 slots available.

**Comment by Visagalis** [comment]
where in new client i can change slots for example from 9 to 15?

**Comment by farin** [comment]
copying private response to be here public:

add additional colors 
https://github.com/farin/JCloisterZone-Client/blob/master/src/renderer/assets/styles/player-colors.scss
add icons (used in task bar when player is active)
icons here https://github.com/farin/JCloisterZone-Client/tree/master/icons
and change slot limit
and increasing limit https://github.com/farin/JCloisterZone-Client/blob/master/src/renderer/store/gameSetup.js#L26

afaik that should be all, then rebuild app
