### ISSUE TITLE
'Abbey and Mayor' and 'Hills and Sheeps' can't be played together.

### ISSUE THREAD

**Issue by davidegalbiati** [farin/JCloisterZone#349]
Placing the Shepherd results in other players seeing a Barn instead with game outputting errors.

**Comment by farin** [comment]
@davidegalbiati which version are you using? Do you have saved game.

Just tried with 5.2.0 and seems to be ok (tried only very basic case)
![Screenshot from 2020-12-03 22-37-18](https://user-images.githubusercontent.com/533295/101091359-56b6b080-35b8-11eb-9258-53a267d64777.png)

**Comment by davidegalbiati** [comment]
Ok I was still playing with the 4.6.1 version. Moving to the last beta release everything works properly.
My sincere compliments for all the work you are doing for this game :)
