### ISSUE TITLE
'Dragon' arrows graphical bug

### ISSUE THREAD

**Issue by davidegalbiati** [farin/JCloisterZone#350]
See screenshots.
Arrows sometimes remain on the screen in apparently ranom positions.
![bug dragonm](https://user-images.githubusercontent.com/75132838/101281621-54c73a00-37d0-11eb-8c34-3ae4522ae49d.png)
![bug dragon2](https://user-images.githubusercontent.com/75132838/101281622-55f86700-37d0-11eb-88e9-7163cc47a2a0.png)

**Comment by farin** [comment]
fixed by https://github.com/farin/JCloisterZone-Client/commit/95624b9fa12f1bbf90f6248813f0ea030e7d15de
