### ISSUE TITLE
Disabling farmers breaks game

### ISSUE THREAD

**Issue by hyzchip** [farin/JCloisterZone#351]
In the new 5 beta, create a new game with any combination of expansions and components.  In the "rules" tab, remove farmers (it doesn't matter if anything else is allowed).  Once the game is started, it is impossible to place any tiles.  You can preview locations and rotate the tile, but it can't be actually placed, rendering the game unplayable.

Apart from that, I must say I love the new version!  It's faster than the previous versions, and the interface is friendlier.

**Comment by farin** [comment]
@hyzchip 
are you using latest (at least 5.2.0) ?
I am unable to reproduce it
I tried production build, base game with excluded farmers - ok
then all major expansions + river and excluded farmers - again ok

Is it reproducible (happening regulary)
If you want to help you may run app in devMode and look into console for error 
About dialog / open config file / change `"devMode": false` to ` "devMode" true` and restart app. You should have dev console open now.
`

**Comment by hyzchip** [comment]
After the upgrade to 5.3.0, I haven't encountered the issue again.  I tried several different expansion combinations, and tiles could always be placed normally, so it appears fixed.

Keep up the good work :+1:
