### ISSUE TITLE
'Magic Portal' issue - can't place meeple when GQ/RFI tile is in play 

### ISSUE THREAD

**Issue by davidegalbiati** [farin/JCloisterZone#352]
After placing a magic portal, player can't place the meeple anywhere, neither on the magic portal tile it self.
The only allowed thing was moving the 'fairy'
![valico maico](https://user-images.githubusercontent.com/75132838/101423744-0e6dfa00-38fa-11eb-9451-c8a9d6ac5755.png)

**Comment by farin** [comment]
@davidegalbiati please save a game next time. This is not general issue with magic portal and seem to be something related to actual game state.

**Comment by farin** [comment]
anyway I got idea and found cause without saved game
happens when all features on current tile are occupied

![image](https://user-images.githubusercontent.com/533295/101834241-61ce8b00-3b3a-11eb-9328-28c2858009d9.png)

**Comment by davidegalbiati** [comment]
This was not my case. As you can see there were a lot of options available. I'll save the game next time :)

**Comment by farin** [comment]
@davidegalbiati I see. Anyway I has scenario in same issue happens and likely the cause will be same. (despite my guess was wrong) going to investigate it

**Comment by farin** [comment]
🤦 in my case it's working. I only have almost everything occupied. Sorry for confusion

**Comment by davidegalbiati** [comment]
Here it is, same problem, I attach the saved game
[valico magioco.zip](https://github.com/farin/JCloisterZone/files/5675909/valico.magioco.zip)

**Comment by farin** [comment]
awesome, that help's a lot, i can see a cause now

**Comment by farin** [comment]
requires Games Quarterly and River to be in play, then it happens on portal tiles

**Comment by farin** [comment]
fixed artwork will be downloaded by 5.3.0 https://github.com/farin/JCloisterZone-Client/commit/034c68ec43076350d5820bfea0c41efe36804fc1
