### ISSUE TITLE
Mouse button deletes the game

### ISSUE THREAD

**Issue by davidegalbiati** [farin/JCloisterZone#354]
Sorry if I'm creating different posts but they need to be separated, I think.
My gaming mouse has lateral buttons. On the internet browsers using these buttons you can move to the next or previous pages in the cronology (usually you do this with the arrows in the top left corner).
While playing Carcassonne, casually hitting the 'previous page' button brought me outside the game to the main page where you can create new game ecc.. and there was no way to go back in the game we were playing.
Luckily I was playing with friends and they, before quitting, were able to save the game and send me the file to restart where we left.
All this to say that probably you should consider disabling this feature or something :)

**Comment by farin** [comment]
definitely yes, that's ugly bug :-)

**Comment by farin** [comment]
hmm, this one is not easy ....

**Comment by farin** [comment]
fixed with https://github.com/farin/JCloisterZone-Client/commit/bc33f486473422319210182f0830756a3e3c0be2
