### ISSUE TITLE
Follower from the city of Carcassonne must be deployed  when shepherd is deployed onto field.

### ISSUE THREAD

**Issue by Testsr** [farin/JCloisterZone#359]
The blue player cannot skip deployment to the city at all. This only seems to occur when the Shepard is deployed.
[CoC issue(2).zip](https://github.com/farin/JCloisterZone/files/5761160/CoC.issue.2.zip)

![JCloisterZone 3_01_2021 2_23_15 PM](https://user-images.githubusercontent.com/31809837/103471059-44a27a80-4dcf-11eb-81a5-98308e6720f0.png)

**Comment by farin** [comment]
already fixed in 0a0ae5adbfe48a12eba71bb279120a0962c69fb6
wille be released asap in 5.4.0
