### ISSUE TITLE
Spelling: Catles?

### ISSUE THREAD

**Issue by Maltavius** [farin/JCloisterZone#360]
![image](https://user-images.githubusercontent.com/10133945/103489746-cbc71100-4e16-11eb-9364-01034eb1e7e3.png)
I guess it's supposed to say Ca**s**tles?

**Comment by farin** [comment]
fixed with https://github.com/farin/JCloisterZone-Client/commit/6ac49c1c18eb6ac825ac71c47f9a6bffafc06238
