### ISSUE TITLE
V 5.3.3. - tile does not rotate on right click

### ISSUE THREAD

**Issue by EngelJ-712** [farin/JCloisterZone#361]
I installed 5.3.3. a few days ago and installed Java 15 for that.
When I am looking where to place a tile, it some times happens that at some locations of the map, the tile is only shown in "possible" orientations when I click with the right button. In the "tile preview" on top of the screen it always rotates in 90 degree steps.
![grafik](https://user-images.githubusercontent.com/76966631/103579007-d5fd1400-4ed7-11eb-95a7-3d135ac10ee0.png)

At other possible locations of the map it rotates to all 4 positions - even if they are not valid.
![grafik](https://user-images.githubusercontent.com/76966631/103579106-02189500-4ed8-11eb-969e-6aece11b7526.png)

First I only observed it related to tiles with roads, but it also happens related to tiles with city parts.

Saved file to reproduce can be supplied.

**Comment by hyzchip** [comment]
The difference between your two examples is that in the first one, this is the only possible orientation.  In the second one, there are three possible orientations.

IIRC, the old 4.x client always skipped impossible orientations; it would be nice to bring this back, I think.

**Comment by farin** [comment]
@hyzchip good point, I am going bring it back.

**Comment by EngelJ-712** [comment]
Thank you both for picking it it up.
