### ISSUE TITLE
Shepherd automaticly grows flock when a field is closed.

### ISSUE THREAD

**Issue by Testsr** [farin/JCloisterZone#363]
There is no indication in the rules that the shepherd must grow his flock if his field is closed.

**Comment by farin** [comment]
I guess this is correct, see

https://wikicarpedia.com/index.php/Hills_%26_Sheep#3._Scoring_a_feature

Exception: If any player completes a field with shepherds and sheep by fully surrounding it by roads and cities, immediately resolve the Guide the flock to the stable action for that field. [1] [2]

**Comment by stanolacko** [comment]
Hmm, my comment dosn't arrived over email.
Question is it current player has to is able to take new token or not.

**Comment by stanolacko** [comment]
Here is @meepledrone rules interpreatation:
When a field is closed, all the shepherds in it are scored, no matter the owner. In practical terms, the only difference is that if you are the active player and your shepherd is in the closed field, you have the option to draw a sheep token before scoring all the shepherds. You will be able to scratch up to 4 more points if you are lucky, but you can also lose all the points for your flock. It's up to you.

**Comment by Testsr** [comment]
@meepledrone's rules interpretation:
These are the options that may happen to you when expanding a field with your shepherd: 
1. You decide to Guide the flock to the stable: you do not push your luck and score right away.
2. You decide to Grow the flock: you push your luck one more time:
   - If you draw a sheep token, you add it to your flock and score it right away.
   - If you draw a wolf token, you score no points
