### ISSUE TITLE
Losing connection and randomize seating order. 5.3.3

### ISSUE THREAD

**Issue by Snearone** [farin/JCloisterZone#365]
Upon being disconnected there is no other way to resume play than saving a game and hosting it from load game option.
Even after geting internet connection back on, previously disconnected player is unable to perform any action.

Can be annoying but it's non game breaking, unles you play with randomize seating order.
It looks like it randomize seats each time you start a game, even from a load game option.

Quick example.
That's how the game was played from the beginning:
![1](https://user-images.githubusercontent.com/77487705/104717673-93caa280-5721-11eb-8a22-5735c5580c4f.png)
After saving and loading a game:
![2](https://user-images.githubusercontent.com/77487705/104717708-9f1dce00-5721-11eb-8c5b-3058472b2866.png)
After loading the same save again:
![3](https://user-images.githubusercontent.com/77487705/104717735-a8a73600-5721-11eb-80a6-c5c4ae38ae19.png)

**Comment by farin** [comment]
@Snearone just side note. Client should be able to connect again to running game simple by using "connect"

**Comment by farin** [comment]
fixed by https://github.com/farin/JCloisterZone-Client/commit/3d7d23372ca207f14cb305743a454f15126b9700

**Comment by Snearone** [comment]
It can't, there is a message "Game already started" trying to do so.
