### ISSUE TITLE
Issue with bridges 5.4.0

### ISSUE THREAD

**Issue by Snearone** [farin/JCloisterZone#367]
All meeples placed on any bridge are displayed in corner of starting tile overlapping each other.

![bridge](https://user-images.githubusercontent.com/77487705/104856363-2a59b800-590a-11eb-9fde-2afb0886e236.png)

**Comment by farin** [comment]
I am going to make hotfix tomorrow.

**Comment by farin** [comment]
fixed https://github.com/farin/JCloisterZone-Client/commit/c53b4ad38b937af91ff87584946c768f809c3d4a
