### ISSUE TITLE
4.x Version: Exeception when placing a meeple "Only deplpy [sic] to the City of Carcassone is allowed"

### ISSUE THREAD

**Issue by ventilator** [farin/JCloisterZone#377]
Problem: When placing a meeple to the street on this highlighted tile, the game crashed in a multiplayer game with "Only deplpy [sic] to the City of Carcassone is allowed"
Note: At this point 10 meeple have been waiting in the City or Carcassone to be placed into the large city, maybe this is crash related

![image](https://user-images.githubusercontent.com/4276067/112729824-81918f80-8f2e-11eb-98f7-c851a5e2e72d.png)
![image](https://user-images.githubusercontent.com/4276067/112729856-a7b72f80-8f2e-11eb-9cd0-f9df94ef358c.png)

The game was not recoverable, save game and error log is available
[error.log](https://github.com/farin/JCloisterZone/files/6216125/error.log)
[crash.zip](https://github.com/farin/JCloisterZone/files/6216128/crash.zip)

**Comment by farin** [comment]
only version 5 is currently maintained
