### ISSUE TITLE
MacOS undo makes all tiles grey for the rest of the game

### ISSUE THREAD

**Issue by tadun** [farin/JCloisterZone#383]
Hello, 
enjoying the game so much, looking forward for the public server hosted games. One issue though. If decide to change the tile or meeple placement, all the tiles turn dark grey. They stay that way for the rest of the game, which makes it really difficult to see them. Not sure if someone had a similar issue, I have the latest version and I tried reinstalling it. 

Thanks

Tadeas

**Comment by farin** [comment]
could you please provide screenshot?

**Comment by tadun** [comment]
ne 25. 4. 2021 v 14:13 odesílatel Roman Krejčík ***@***.***>
napsal:

**Comment by farin** [comment]
sorry, no image here

**Comment by tadun** [comment]
How about now?
[image: Screen Shot 2021-04-25 at 2.22.02 PM.png]

po 26. 4. 2021 v 7:58 odesílatel Roman Krejčík ***@***.***>
napsal:

**Comment by stanolacko** [comment]
@tadun try to include that picture not to mail, but directly on github.com
at https://github.com/farin/JCloisterZone/issues/383

**Comment by tadun** [comment]
<img width="1440" alt="Screen Shot 2021-04-25 at 2 22 02 PM 11 18 31 AM" src="https://user-images.githubusercontent.com/56317154/116146191-7fae1e00-a6de-11eb-91c6-3da6508994c9.png">

**Comment by tadun** [comment]
![jcloister](https://user-images.githubusercontent.com/56317154/116146382-bbe17e80-a6de-11eb-955b-7f6f479e2f34.png)

**Comment by stanolacko** [comment]
@tadun Great, thank you!

**Comment by farin** [comment]
should be already fixed
