### ISSUE TITLE
Bridges, Castles and Bazaars [BUGS]

### ISSUE THREAD

**Issue by davidegalbiati** [farin/JCloisterZone#384]
1) During Bazaar, if someone bet 3 (example) I'm able to ALSO bet less than 3, and this should not be possible.
2) Sometimes happens that during bazaar, bets are scored properly to player but in the timeline you only see the minus
   [Example: I bet 5, other player sells, I pay 5, he score 5, but in timeline only appears -5 and not his +5]

**Comment by farin** [comment]
client change https://github.com/farin/JCloisterZone-Client/commit/cf998ab33620f1f978173a77364b9b60bdb65328

**Comment by farin** [comment]
and second point
https://github.com/farin/JCloisterZone-Client/commit/5a620fdcaaef777c7c660c823f7f4a1daee4ce35
