### ISSUE TITLE
Graphical mistake when scoring fields

### ISSUE THREAD

**Issue by WGFizban** [farin/JCloisterZone#386]
I found a small bug in the graphical interface. It is about displaying the points for the fields (during and after the game). I thought it was a counting error, but it's just a graphical mistake. Take a look at the screenshots. On the second, the graphic representation corrected by me.  (According to the rules, the pig, of course, also affects small castles ) 
There is also a small suggestion that it will be more readable to indicate first the amount of the scored structure and then the points for it.
![image](https://user-images.githubusercontent.com/63311150/117533647-2dc69b80-afee-11eb-9440-84359daca211.png)
![image](https://user-images.githubusercontent.com/63311150/117533663-459e1f80-afee-11eb-85cb-58d372ecb99f.png)

**Comment by farin** [comment]
just adding note here, +1 for castle seems to be correct as you saying http://www.carcassonnecentral.com/community/index.php?topic=1754.0
