### ISSUE TITLE
Board.remove(Tile) does not update Board.availMoves correctly in 2.6, affecting AI

### ISSUE THREAD

**Issue by TripleWhy** [farin/JCloisterZone#40]
This is my understanding of the AI:
When the AI tries different actions, it creates a SavePoint, places a tile and maybe a meeple, rates the position, and restores the simulation game to the save point.
The SavePointManager undos the tile placement.
To do so, it calls Board.remove(Tile), which removes the tile and updates availMoves.

Now here is the problem: add(Tile) updates availMoves for adjacent open positions and adds the edges of the new tile to their EdgePatterns. Which is good. However, remove() does not undo this. It only removes positions that are no longer reachable.
Thus the edge patterns get filled while trying each possible action. Therefore the AI thinks that positions that are tried later are more difficult to close, because the edge patterns have fewer wildcards than they actually should have.

I analyzed this only for the code of 2.6 (commit 453560). So if it's already solved, ignore this post ;-)

**Comment by farin** [comment]
no longer valid
