### ISSUE TITLE
play online: support "offline" game creation

### ISSUE THREAD

**Issue by farin** [farin/JCloisterZone#407]
persis game even not all players are online and let correspondent join

**Comment by stanolacko** [comment]
It will be also possible to continue this by "offline" play? in mode turn - by - turn? I guess, it is can be by previous game state and own engine to calculate points, etc after playing, hmm?

**Comment by farin** [comment]
offline play is already possible, you can leave and resume game anytime. 
Except game end, because when you finished game it's auto removed from your game list. This must be changed.

**Comment by stanolacko** [comment]
So, don't needed to join other party to play next turn? Great!

**Comment by farin** [comment]
done
