### ISSUE TITLE
Not fully functional tile from GQ expansion.

### ISSUE THREAD

**Issue by Snearone** [farin/JCloisterZone#410]
You can't put a meeple on anything on this CcCR tile from GQ expansion:
![ccrc](https://user-images.githubusercontent.com/77487705/136546142-739b54fc-61db-4757-b81f-8a8299e606f1.png)
Only under one condition, which is: connecting this tile to claimed road, allows meeple placement on city/field on that tile.
This tile also breaks other expansions, for example magic portals works till this tile is drawn, when it is on a board, not only magic portals stop working, but all features on magic portal tile.

**Comment by farin** [comment]
seems to be ok in latest app
