### ISSUE TITLE
Hills not apply on scoring fields

### ISSUE THREAD

**Issue by stanolacko** [farin/JCloisterZone#414]
In final scoring, 2 yellow on hills and 2 black - 1 on regular tile, 2nd on on regular tiles. By rules tie by power, compared meeples on hills 2:1 - yellow is owner of field.
But in 2.9.0 Both scored 36 points.
[not-hills.txt](https://github.com/farin/JCloisterZone/files/7636516/not-hills.txt)

**Comment by farin** [comment]
default tie breaker is just presenc on hill(s), regardless of count

there is rule switch to enable also meeples comparison 
not issue
