### ISSUE TITLE
Map dragging locking to mouse

### ISSUE THREAD

**Issue by kbkk97** [farin/JCloisterZone#416]
Dragging the map seems to sometimes lock onto the mouse and won't let go, Possibly clicking when other players are placing tiles? Not too sure. Only way to seemingly fix it is to maniacally spam mouse buttons and keyboards presses till it releases me from my suffering.

Edit: It appears you can free yourself by double-clicking the left button, maybe the issue is caused by highlighting?

**Comment by farin** [comment]
seem's like bug in logic which distinguish between click and drag (because very short drag must be interpreted as click)
looking at it...

**Comment by farin** [comment]
hopefully fixed with https://github.com/farin/JCloisterZone-Client/commit/2a204541734cc241bafc01093322c89686c34336
