### ISSUE TITLE
Allow Place Barn when not playing Farmers

### ISSUE THREAD

**Issue by stanolacko** [farin/JCloisterZone#423]
Game rule for Farmers can affect not only #422 Placement of shepherd, but also placement of Barns.
When Barns is included into game, it has to have able also to play.
Rule.FARMERS has to disable placement of regular meeples as farmers, like Small / Big Meeple or Ringmaster.
All other placements of other meeples or tokens to field should to be allowed.

**Comment by farin** [comment]
I agree
