### ISSUE TITLE
Flying machine and Towers issue

### ISSUE THREAD

**Issue by davidegalbiati** [farin/JCloisterZone#437]
Two meeples on the same tile due to a previews flying machine, it was impossible to select which of the two meeples remove with the tower

**Comment by stanolacko** [comment]
@davidegalbiati it's good to include a save of game for test that scenario. Because there can be multiple different options and only one if buggy, but which one?

**Comment by farin** [comment]
i think that score badges shoudn;t interact with mous int this case and also be semi transparent
