### ISSUE TITLE
When chatting in-game AI player names may be shown

### ISSUE THREAD

**Issue by joelpurra** [farin/JCloisterZone#66]
The order of player chat name detection seems to be active > human > ai. If the active player is an ai player, then the ai name is used for chat messages even though it's clearly a human using the chat feature.
https://github.com/farin/JCloisterZone/blob/d2f3051befaf3ffcfe57fbcc9849224260214a3b/src/main/java/com/jcloisterzone/ui/controls/ChatPanel.java#L231

Tested with the `config.yaml` line
```yaml
ai_place_tile_delay: 10000 # miliseconds to wait before computer player place tile
```

**Comment by joelpurra** [comment]
@farin: great! Will try it out next time "our group" is playing =)

**Comment by joelpurra** [comment]
@farin: it seemed to work for AI players when tested with two players.

We (four players) did experience other problems, confirmed by all participants:

- Only the player of the same machine showed up for one game.
- The chat window is blank on Mac. During one game it also flashed black at times.

**Comment by farin** [comment]
@joelpurra: is chat window always blank on Mac? What JVM is used? I changed way how panels are layouted to grid and issues can definitely appear here.

**Comment by joelpurra** [comment]
@farin: the chat window was in use during one normal game, and one test game. It never showed any text. I could not see my own nor other players' text. Then I say the panel flashed black, I mean the area above the chat input box - the input box was still visible. The version used was 8abd756.

Java on Mac is tricker than java on Windows in some ways.

- The default java version on Mac OS X 10.10 is `1.6.0.jdk`. Apple [made java selection harder](http://apple.stackexchange.com/questions/57986/multiple-java-versions-support-on-os-x-and-java-home-location) than it used to be since OS X 10.8, so it can be assumed "all" Mac users use `1.6.0.jdk`.
- As a developer, I could also change JDK to for example `jdk1.7.0_45.jdk`, but this is an exception.

Looking at files in use by the process running JCZ it looks like `1.6.0.jdk`.
