### ISSUE TITLE
Take Screenshots

### ISSUE THREAD

**Issue by Decar** [farin/JCloisterZone#76]
Often we take screenshots during a game or usually at the very end and taking Print Screens can be laborious.  I think it would be beneficial for users to be able to automatically save the GridLayout where tiles are placed.

@farin has rightly pointed out that most games automatically produce files such as: Screenshot_001.png rather than display a JFileChooser.

@joelpurra has also stated that we should not assume the user has write-access to the JCZ directory under screenshot; instead it should write to a default directory such as the user's home folder (like My Documents).

I have mixed opinions on the approach, as a novice JCZ user how will I know where files will be written?  The JFileChooser seems to mitigate this.

To add to this last point, I think it would be sensible to introduce a new Config item such as: default_screenshot_folder so that user's can override the default folder.

**Comment by Cu8eR** [comment]
@farin - is possible to add a feature - automatically take a screenshot after game (with score table)

**Comment by farin** [comment]
@Cu8eR I want to keep automatically result of each online game available under private url. Than it should be linkable and it will contain also screenshot
