### ISSUE TITLE
Prepared Games

### ISSUE THREAD

**Issue by Decar** [farin/JCloisterZone#77]
Some people at carcassonne-central suggested a new feature; basically allow people to prepare the tiles to use in a game, so that the order of the tiles is pre-determined.  This can be used to set up puzzles for users to load into JCZ and determine the 'best' strategy for a match.  When the list of prepared tiles is completed, the game should either end or continue at random, determined by the puzzle creator.

Such a feature would need:
- A mechanism for the puzzle creator to define the order in which tiles are placed.
- A mechanism for the puzzle creator to define a list of discarded tiles.
- Make sure that the list of tiles is stored, so that puzzles can be saved and loaded by users.
- Make sure users are aware of the number of perpared tiles in the deck.

I've made a start at implementing these features at  https://github.com/Decar/JCloisterZone/tree/prepared-games
### Defining a draw sequence

Currently, it seemed logical that a puzzle creator loads a YAML file (such as prepared.yaml) to define the draw sequence and discarded tiles, this is essentially the same as the debug operatives currently in place:

```
draw:
  - BA.RCr
  - BA.C
  - BA.CccR
  - BA.Rr
  - BA.Ccc+
  - CA.Cc+
  - AM.C!+
  - .    #A Dot should indicate that the game ends at this point.
discard:
  - BA.L
  - BA.Lr
```

I've created a PreparedGameConfigLoader and PreparedGameConfig to load the yaml file into an Object which can be used every time a game is started.
### Loading YAML file into PreparedGameConfig

The PreparedGameConfig should be created at the start of every game, unlike the existing Config which loads when JCZ starts.  I think it makes sense to add a _preparePreparedGame_ method to the CreateGamePhase, as other game components are set up at this time.
### Saving the game state

I think it's important to indicate that the Game is now a Prepared Game and that this is recorded in the Snapshot XML.
It seems logical that the snapshot contains the list of remaining prepared tiles left to play, so that someone completing the puzzle does not need to mess about with configuration files.  Just load the save file:

Here's a proposed example save file:

```
...
<game app-version="dev-snapshot" phase="com.jcloisterzone.game.phase.TilePhase" prepared-game="true">  ###A new value for prepared
...
<tiles next="BA.CccR">
...
<prepared name="BA.Rr"/>  ###A record for each prepared tile remaning
<prepared name="BA.Ccc+"/>
</tiles>
</game>
```
### Drawing a Tile

Currently the _number_ of the next drawn tile is determined in the SimpleServer class in the _handleGetRandSample_ method and this fires an event which is read by the DrawPhase.

Yesterday, I swapped out the DrawPhase with a PreparedDrawPhase, but now I see that the Tile ID should be determined by the SimpleServer.  This is a much simpler solution.  What I'm not clear about is what should happen if the game ends early; but the DEBUG code should provide a clear enough example.
### Displaying a Prepared Game

I think it makes sense to include a new value on the right hand side to indicate the number of prepared tiles left in the deck; it will be clear to someone playing that the Game is of a different type.

**Comment by x-iso** [comment]
Yes, list of remaining tiles should be an option for a game setup. Can be helpful and evens out a bit strategy level of newbies and experienced players.

**Comment by farin** [comment]
possible by annotatons section in saved games

see integration test which in common use "prepared games" wth defined tile order
eg
https://github.com/farin/JCloisterZone/blob/master/src/test/resources/saved-games/inns_and_cathedrals/cathedralsScoring.jcz
