### ISSUE TITLE
Don't write files to the `JCloisterZone.jar` directory

### ISSUE THREAD

**Issue by joelpurra** [farin/JCloisterZone#79]
It seems several files are written to the game directory by default. Yes, JCZ developers may use a writeable location when debugging, but it's both bad practice to write there and assume that it's writeable for others. Would still prefer a more standardized per-user storage location.

Keep in mind that Windows did a move against users having write access to program folders several years ago - "old programs that don't know better" now write to a virtual folder structure that is hidden in a completely different place (per user). Unix-based systems have had non-writeable application locations longer than that.

In lack of proper multi-platform "My Documents"/"My Save Games" path usage (unless there's a good library), `System.getProperty("user.home")` seems like a good start. There's also `String DefaultFolder=new JFileChooser().getFileSystemView().getDefaultDirectory().toString();` and (for Windows) `System.getenv("USERPROFILE")`. Some strings seem Windows language dependent, like `%USERPROFILE%\Saved Games`
http://stackoverflow.com/questions/9677692/getting-my-documents-path-in-java
http://stackoverflow.com/questions/5590040/cross-platform-way-to-ask-for-the-users-documents-folder
https://en.wikipedia.org/wiki/Special_folder

**Comment by farin** [comment]
request for comment http://www.carcassonnecentral.com/community/index.php?topic=1393

**Comment by farin** [comment]
resolution: work dir will be game dir if writeable, other ways APP_DATA/... or ~/.jcloisterzone is ised
