### ISSUE TITLE
Add git tags to released versions

### ISSUE THREAD

**Issue by joelpurra** [farin/JCloisterZone#85]
if `git tag -a v3.1.0 -m v3.1.0 <commit of the release> && git push origin v3.1.0` was used, then it would be easier to tag debug build, like `git describe --tags --match 'v[0-9]*' --always --dirty='-SNAPSHOT'`.

**Comment by farin** [comment]
all new releases are alredy tagged

**Comment by joelpurra** [comment]
@farin: great, thanks!
