### ISSUE TITLE
No warning to the user if plugin folder or files are missing

### ISSUE THREAD

**Issue by joelpurra** [farin/JCloisterZone#86]
When I've played debug builds with a group of friends, some have misunderstood the instructions and not installed the `plugin/` folder together with `JCloisterZone.jar`. The game can start, except the players who haven't installed it correctly can't play their turn as they don't see any tiles.

A warning (error) that plugin files are missing would be in place.

**Comment by farin** [comment]
no relevant for a new client 5.x
