### ISSUE TITLE
3.1-alpha: Some items are not completely visible in PlayerPanel.

### ISSUE THREAD

**Issue by fatsu** [farin/JCloisterZone#89]
Some items are not completely visible in PlayerPanel.

![issue](https://cloud.githubusercontent.com/assets/10167314/5613041/7f795422-94de-11e4-9518-a9962a021e06.jpg)

**Comment by farin** [comment]
what is your system & JVM please?

**Comment by fatsu** [comment]
Windows 7.

java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

**Comment by farin** [comment]
@fatsu did you make something special woth it? eg resizing etc. I am not able to ovserve in Win7 neither Ubuntu
(but i test it only with newer jvm 1.7.0-67)

**Comment by fatsu** [comment]
@farin 
No, nothing special. It happens fullscreen as well as custom size screen. We observed this on several machines. 
I just tried the 3.1-alpha2 here at home on win7 with java 1.8.0_25-b18 and it gave the same. Haven't tried it with the latest master branch yet.

Question: why don't you systematically tag the commits you use for releases (only 2.7 until now), even alpha or beta ones. Would it not be easier for contributers to find their way and add bugfixes against a specific version?

**Comment by farin** [comment]
@fatsu good point with tags. Simply question is that I personally didn't need to go back deep and latest commts in relaease branch was enough for me. So nothing push me to add tags. But you right it should be here.

**Comment by farin** [comment]
latest master probably won't change anything, i focused to online server last 14 days.

**Comment by farin** [comment]
i finally reproduce it. thanks
