### ISSUE TITLE
Corn circle panel is not closed when choice has been made by remote player

### ISSUE THREAD

**Issue by jetthe** [farin/JCloisterZone#97]
When a corn circle tile is played the corn circle panel is shown for the remote players but it's not closed when a choice is made by the player who played the tile. This renders a dead lock in the game the next time a corn circle tile is played as the buttons on the panel are not reactivated.

I'm not sure if the best behaviour is that the corn circle panel is shown for all players and not just for the player playing the corn circle tile. One might argue that it would be better to just show the panel if a local player is able to make a choice.

**Comment by farin** [comment]
my motivation to show panel is indicate that game is not stuck but it is waiting fo remote action.

**Comment by farin** [comment]
ui for remote players is not ideal. Adding improvement to TODO list. Now just hiding is fixed.
